/**
 * Demo seed for ETE when registry is empty (dev / BAT).
 * Assignees prefer the signed-in user so Planner "Mine" is populated.
 */

import { ETE_PREDEFINED_DESCRIPTIONS, ETE_TASK_TYPES } from "@/constants/enterprise-task-engine";
import { isDemoSeedEnabled } from "@/lib/demo-seed";
import { getStoredUser } from "@/lib/auth";
import { listEteTasks, registerEteTask } from "./task-registry";

export function ensureEnterpriseTasksDemoSeed(): void {
  if (!isDemoSeedEnabled()) return;
  if (listEteTasks().length > 0) return;
  const now = Date.now();
  const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString();
  const user = typeof window !== "undefined" ? getStoredUser() : null;
  const me = user?.id ? `user:${user.id}` : "employee:rm-001";
  const mgr = "employee:mgr-001";

  const seeds: Parameters<typeof registerEteTask>[0][] = [
    {
      taskType: ETE_TASK_TYPES.OPPORTUNITY,
      category: "workflow",
      assigneeRef: me,
      opportunityRef: "opp-demo-001",
      entityKind: "Opportunity",
      entityId: "opp-demo-001",
      title: "Follow-up Documents",
      workType: "Document Collection",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.FOLLOW_UP_DOCUMENTS,
      dueOn: iso(2 * 60 * 60 * 1000),
      reportingManagerRef: mgr,
      assignedByRef: mgr,
      borrowerName: "Priya Nair",
      loanProduct: "Home Loan",
      lenderName: "HDFC Bank",
      grossStage: "Document Center",
      priority: "high",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.OPPORTUNITY,
      category: "workflow",
      assigneeRef: me,
      opportunityRef: "opp-demo-002",
      entityKind: "Opportunity",
      entityId: "opp-demo-002",
      title: "Follow-up Lender",
      workType: "Lender Call",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.FOLLOW_UP_LENDER,
      dueOn: iso(-26 * 60 * 60 * 1000),
      reportingManagerRef: mgr,
      assignedByRef: mgr,
      borrowerName: "Arjun Mehta",
      loanProduct: "LAP",
      lenderName: "ICICI Bank",
      grossStage: "Lender Pipeline",
      priority: "high",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.OPPORTUNITY,
      category: "workflow",
      assigneeRef: me,
      opportunityRef: "opp-demo-003",
      entityKind: "Opportunity",
      entityId: "opp-demo-003",
      title: "Customer Meeting",
      workType: "Customer Call",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.CUSTOMER_MEETING,
      dueOn: iso(26 * 60 * 60 * 1000),
      assignedByRef: mgr,
      borrowerName: "Sneha Kapoor",
      loanProduct: "Personal Loan",
      grossStage: "Opportunity Workspace",
      priority: "medium",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.OPPORTUNITY,
      category: "workflow",
      assigneeRef: "employee:ops-001",
      opportunityRef: "opp-demo-004",
      entityKind: "Opportunity",
      entityId: "opp-demo-004",
      title: "Verify CIBIL",
      workType: "Verification",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.VERIFY_CIBIL,
      dueOn: iso(4 * 24 * 60 * 60 * 1000),
      assignedByRef: "employee:mgr-001",
      borrowerName: "Vikram Shah",
      loanProduct: "Home Loan BT",
      lenderName: "SBI",
      grossStage: "Credit Workbench",
      priority: "medium",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.INDEPENDENT,
      category: "general",
      assigneeRef: me,
      entityKind: "Workflow",
      entityId: "org-ops",
      title: "Personal — Pipeline note",
      workType: "Internal Review",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.INTERNAL_REVIEW,
      description: "Draft weekly pipeline note",
      dueOn: iso(5 * 60 * 60 * 1000),
      department: "Sales",
      assignedByRef: "employee:mgr-001",
      priority: "medium",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.INDEPENDENT,
      category: "general",
      assigneeRef: "employee:ops-001",
      entityKind: "Workflow",
      entityId: "org-ops",
      title: "Weekly ops standup prep",
      workType: "Internal Review",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.INTERNAL_REVIEW,
      description: "Weekly ops standup prep",
      dueOn: iso(10 * 24 * 60 * 60 * 1000),
      department: "Operations",
      assignedByRef: "employee:mgr-001",
      priority: "low",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.OPPORTUNITY,
      category: "workflow",
      assigneeRef: me,
      opportunityRef: "opp-demo-005",
      entityKind: "Opportunity",
      entityId: "opp-demo-005",
      title: "Sanction Follow-up",
      workType: "Follow-up",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.FOLLOW_UP_LENDER,
      description: "Sanction follow-up with lender credit desk.",
      dueOn: iso(2 * 24 * 60 * 60 * 1000),
      assignedByRef: "employee:mgr-001",
      borrowerName: "Neha Joshi",
      loanProduct: "Home Loan",
      lenderName: "Axis Bank",
      grossStage: "Lender Pipeline",
      priority: "critical",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.OPPORTUNITY,
      category: "workflow",
      assigneeRef: me,
      opportunityRef: "opp-demo-006",
      entityKind: "Opportunity",
      entityId: "opp-demo-006",
      contactId: "contact-demo-006",
      title: "Site Visit — Property Inspection",
      workType: "Verification",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.CUSTOMER_MEETING,
      description: "Coordinate site visit with valuation.",
      dueOn: iso(50 * 60 * 60 * 1000),
      assignedByRef: "employee:mgr-001",
      borrowerName: "Arjun Mehta",
      loanProduct: "LAP",
      grossStage: "Document Center",
      priority: "high",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.OPPORTUNITY,
      category: "workflow",
      assigneeRef: "employee:ops-001",
      opportunityRef: "opp-demo-007",
      entityKind: "Opportunity",
      entityId: "opp-demo-007",
      title: "Disbursement Coordination",
      workType: "Approval",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.FOLLOW_UP_LENDER,
      description: "Confirm disbursement checklist with customer.",
      dueOn: iso(5 * 24 * 60 * 60 * 1000),
      assignedByRef: "employee:mgr-001",
      borrowerName: "Priya Nair",
      loanProduct: "Home Loan",
      lenderName: "HDFC Bank",
      grossStage: "Disbursement",
      priority: "high",
      createdBy: "system",
    },
    {
      taskType: ETE_TASK_TYPES.OPPORTUNITY,
      category: "workflow",
      assigneeRef: me,
      opportunityRef: "opp-demo-008",
      entityKind: "Opportunity",
      entityId: "opp-demo-008",
      contactId: "contact-demo-008",
      title: "Email Follow-up — Missing KYC",
      workType: "Follow-up",
      status: "open",
      predefinedDescription: ETE_PREDEFINED_DESCRIPTIONS.FOLLOW_UP_DOCUMENTS,
      description: "Send KYC reminder email.",
      dueOn: iso(8 * 60 * 60 * 1000),
      assignedByRef: "employee:mgr-001",
      borrowerName: "Sneha Kapoor",
      loanProduct: "Personal Loan",
      priority: "medium",
      createdBy: "system",
    },
  ];

  for (const seed of seeds) {
    registerEteTask(seed);
  }
}
