/**
 * CO-WP-103B / Experience Engine seed — Partner Home experience packages.
 *
 * Temporary Enterprise catalogue until the Enterprise Experience Engine
 * admin surface owns these packages. Companion apps must NEVER hardcode
 * this content — they render Partner Home API DTOs only.
 *
 * Catalyst One decides who sees what. The Wealth Partner App presents.
 */

export const PARTNER_HOME_EXPERIENCE_ENGINE = {
  source: "enterprise_experience_engine_seed",
  surface: "wealth_partner_home",
  sprint: "CO-WP-103.20",
} as const;

export const PARTNER_HOME_SAARTHI = {
  headline: "Need Help?",
  askCtaLabel: "Ask Saarthi",
  message: "Ask Saarthi anything.",
  deepLink: "/app/saarthi",
  audience: "wealth_partners",
  priority: 100,
  sortOrder: 0,
  visibilityRule: null,
  schedule: null,
  personalisationKey: null,
  capabilities: [
    {
      id: "voice",
      label: "Voice",
      kind: "voice",
      enabled: false,
      priority: 40,
      sortOrder: 0,
      visibilityRule: null,
      personalisationKey: null,
    },
    {
      id: "chat",
      label: "Chat",
      kind: "chat",
      enabled: false,
      priority: 30,
      sortOrder: 1,
      visibilityRule: null,
      personalisationKey: null,
    },
    {
      id: "training",
      label: "Training",
      kind: "training",
      enabled: false,
      priority: 20,
      sortOrder: 2,
      visibilityRule: null,
      personalisationKey: null,
    },
    {
      id: "recommendations",
      label: "Recommendations",
      kind: "recommendations",
      enabled: false,
      priority: 10,
      sortOrder: 3,
      visibilityRule: null,
      personalisationKey: null,
    },
  ],
} as const;

/**
 * CO-WP-103.1 — Greeting spotlight lines (Experience Engine seed).
 * Companion rotates these; do not invent copy in the app.
 */
export const PARTNER_HOME_GREETING_SPOTLIGHTS = [
  { id: "greet-welcome", text: "Welcome back!" },
  { id: "greet-productive", text: "Have a productive day." },
  { id: "greet-campaign", text: "A new campaign is waiting." },
  { id: "greet-opportunities", text: "Today's opportunities await." },
  { id: "greet-training", text: "New training available." },
] as const;

/** Compact “My Business Today” chip kinds (counts projected by Enterprise). */
/** CO-WP-103.10 — My Business Today quick-glance chips (Experience Engine seed). */
export const PARTNER_HOME_MY_BUSINESS_TODAY_META = {
  title: "My Business Today",
} as const;

export const PARTNER_HOME_TODAY_CHIP_CATALOG = [
  {
    id: "chip-follow-ups",
    kind: "follow_ups",
    label: "Follow Ups",
    icon: "phone",
    theme: "teal",
    count: 0,
    deepLink: "/app/tasks",
    audience: "wealth_partners",
    priority: 100,
    visibilityRule: null,
  },
  {
    id: "chip-documents",
    kind: "documents_pending",
    label: "Documents Pending",
    icon: "upload",
    theme: "amber",
    count: 0,
    deepLink: "/app/documents",
    audience: "wealth_partners",
    priority: 96,
    visibilityRule: null,
  },
  {
    id: "chip-meetings",
    kind: "meetings",
    label: "Meetings Today",
    icon: "calendar",
    theme: "royal",
    count: 0,
    deepLink: "/app/tasks",
    audience: "wealth_partners",
    priority: 92,
    visibilityRule: null,
  },
  {
    id: "chip-targets",
    kind: "targets_due",
    label: "Targets Due",
    icon: "target",
    theme: "crimson",
    count: 0,
    deepLink: "/app/vgrow",
    audience: "wealth_partners",
    priority: 90,
    visibilityRule: null,
  },
  {
    id: "chip-birthdays",
    kind: "birthdays",
    label: "Birthdays",
    icon: "gift",
    theme: "violet",
    count: 0,
    deepLink: "/app/customers",
    audience: "wealth_partners",
    priority: 86,
    visibilityRule: null,
  },
  {
    id: "chip-replies",
    kind: "customer_replies",
    label: "Customer Replies",
    icon: "reply",
    theme: "emerald",
    count: 0,
    deepLink: "/app/dialogue",
    audience: "wealth_partners",
    priority: 84,
    visibilityRule: null,
  },
] as const;

/** @deprecated prefer PARTNER_HOME_TODAY_CHIP_CATALOG */
export const PARTNER_HOME_TODAY_CHIP_LABELS = {
  follow_ups: "Follow Ups",
  documents_pending: "Documents Pending",
  meetings: "Meetings Today",
  birthdays: "Birthdays",
  callbacks: "Callbacks",
} as const;

/** Experience Engine — hero carousel packages (not companion-local content). */
export const PARTNER_HOME_HERO_EMPTY_STATE = {
  title: "Fresh stories are on the way",
  subtitle: "Enterprise will publish campaigns and updates for your customers here.",
  theme: "navy",
  illustrationKey: "hero",
} as const;

/**
 * CO-WP-103.15 — Empty State Experience catalog (Experience Engine seed).
 * Companion renders these — never invents empty-state copy.
 */
export const PARTNER_HOME_EMPTY_STATES = [
  {
    id: "empty-hero",
    kind: "hero",
    illustrationKey: "hero",
    title: "No Hero Cards yet",
    message: "Your spotlight stage is ready — Enterprise will light it up with campaigns soon.",
    ctaLabel: "Browse Marketing",
    deepLink: "/app/marketing",
    theme: "navy",
  },
  {
    id: "empty-campaigns",
    kind: "campaigns",
    illustrationKey: "campaigns",
    title: "No Campaigns yet",
    message: "Great campaigns start with a quiet moment — yours will appear here when Enterprise publishes.",
    ctaLabel: "Open Marketing Center",
    deepLink: "/app/marketing",
    theme: "rose",
  },
  {
    id: "empty-feed",
    kind: "feed",
    illustrationKey: "feed",
    title: "No Feed updates",
    message: "Your Business Feed is clear — a perfect time to check in with a customer.",
    ctaLabel: "Find Customers",
    deepLink: "/app/customers",
    theme: "teal",
  },
  {
    id: "empty-notifications",
    kind: "notifications",
    illustrationKey: "notifications",
    title: "No Notifications",
    message: "You're all caught up — enjoy the calm, and stay ready for the next opportunity.",
    ctaLabel: "Back to Home",
    deepLink: "/app/home",
    theme: "mint",
  },
  {
    id: "empty-business",
    kind: "business",
    illustrationKey: "business",
    title: "No Business items",
    message: "A clear desk means room to grow — start with a follow-up or a new conversation.",
    ctaLabel: "View Tasks",
    deepLink: "/app/tasks",
    theme: "gold",
  },
  {
    id: "empty-training",
    kind: "training",
    illustrationKey: "training",
    title: "No Training yet",
    message: "Learning unlocks confidence — new modules will land here from Enterprise VGrow.",
    ctaLabel: "Open VGrow",
    deepLink: "/app/vgrow",
    theme: "indigo",
  },
  {
    id: "empty-documents",
    kind: "documents",
    illustrationKey: "documents",
    title: "No Documents",
    message: "Your document tray is empty — upload when ready, or revisit a customer file.",
    ctaLabel: "Go to Documents",
    deepLink: "/app/documents",
    theme: "amber",
  },
  {
    id: "empty-actions",
    kind: "actions",
    illustrationKey: "business",
    title: "No Actions right now",
    message: "You're ahead of the curve — recommended actions will appear when Enterprise has a nudge.",
    ctaLabel: "Ask Saarthi",
    deepLink: "/app/saarthi",
    theme: "emerald",
  },
  {
    id: "empty-highlights",
    kind: "highlights",
    illustrationKey: "feed",
    title: "No Highlights today",
    message: "Quiet mornings become strong afternoons — highlights will show when something shines.",
    ctaLabel: "Explore Opportunities",
    deepLink: "/app/opportunities",
    theme: "violet",
  },
] as const;

/** CO-WP-103.2A — Reusable Hero Card Library (Experience Engine seed). */
export const PARTNER_HOME_HERO_CATALOG = [
  {
    id: "hero-home-loan",
    contentType: "home_loan_campaign",
    title: "Home Loan Campaign",
    subtitle: "A refined proposition your customers will remember.",
    imageUrl: null,
    illustrationKey: "home",
    theme: "emerald",
    backgroundGradient: null,
    ctaLabel: "Explore →",
    ctaAction: "explore",
    deepLink: "/app/marketing",
    badge: "🎁 CAMPAIGN",
    productCategory: "Home Loan",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 100,
    sortOrder: 1,
  },
  {
    id: "hero-lap",
    contentType: "loan_against_property",
    title: "Loan Against Property",
    subtitle: "Unlock property value with a premium LAP conversation.",
    imageUrl: null,
    illustrationKey: "building",
    theme: "gold",
    backgroundGradient: null,
    ctaLabel: "Know More →",
    ctaAction: "know_more",
    deepLink: "/app/campaigns",
    badge: "⭐ FEATURED",
    productCategory: "Loan Against Property",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 96,
    sortOrder: 2,
  },
  {
    id: "hero-bl",
    contentType: "business_loan",
    title: "Business Loan",
    subtitle: "Working capital crafted for ambitious SME owners.",
    imageUrl: null,
    illustrationKey: "briefcase",
    theme: "navy",
    backgroundGradient: null,
    ctaLabel: "Apply Now →",
    ctaAction: "apply_now",
    deepLink: "/app/marketing",
    badge: "🔥 HOT OFFER",
    productCategory: "Business Loan",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 94,
    sortOrder: 3,
  },
  {
    id: "hero-mutual-funds",
    contentType: "mutual_funds",
    title: "Mutual Funds Desk",
    subtitle: "Curated wealth conversations for long-term investors.",
    imageUrl: null,
    illustrationKey: "growth",
    theme: "midnight",
    backgroundGradient: null,
    ctaLabel: "Explore →",
    ctaAction: "explore",
    deepLink: "/app/marketing",
    badge: "⭐ FEATURED",
    productCategory: "Mutual Funds",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 92,
    sortOrder: 4,
  },
  {
    id: "hero-insurance",
    contentType: "insurance",
    title: "Protection Suite",
    subtitle: "Insurance conversations that protect families with elegance.",
    imageUrl: null,
    illustrationKey: "insurance",
    theme: "charcoal",
    backgroundGradient: null,
    ctaLabel: "Know More →",
    ctaAction: "know_more",
    deepLink: "/app/campaigns",
    badge: "🏆 EXCLUSIVE",
    productCategory: "Insurance",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 90,
    sortOrder: 5,
  },
  {
    id: "hero-festival",
    contentType: "festival_campaign",
    title: "Festival Offer",
    subtitle: "Seasonal creatives ready for your next customer message.",
    imageUrl: null,
    illustrationKey: "gift",
    theme: "burgundy",
    backgroundGradient: null,
    ctaLabel: "View Details →",
    ctaAction: "view_details",
    deepLink: "/app/campaigns",
    badge: "🎁 CAMPAIGN",
    productCategory: "Festival Offer",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 98,
    sortOrder: 6,
  },
  {
    id: "hero-contest",
    contentType: "contest",
    title: "Partner Contest",
    subtitle: "Climb the leaderboard — rewards go live this week.",
    imageUrl: null,
    illustrationKey: "trophy",
    theme: "purple",
    backgroundGradient: null,
    ctaLabel: "Explore →",
    ctaAction: "participate",
    deepLink: "/app/vgrow",
    badge: "🎯 TARGET",
    productCategory: "Contest",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 88,
    sortOrder: 7,
  },
  {
    id: "hero-training",
    contentType: "training",
    title: "Masterclass Training",
    subtitle: "A short briefing that sharpens your product conversations.",
    imageUrl: null,
    illustrationKey: "training",
    theme: "midnight",
    backgroundGradient: null,
    ctaLabel: "Watch Now →",
    ctaAction: "start_training",
    deepLink: "/app/vgrow",
    badge: "🎓 TRAINING",
    productCategory: "Training",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 84,
    sortOrder: 8,
  },
  {
    id: "hero-roi",
    contentType: "roi_revision",
    title: "New ROI Update",
    subtitle: "Fresh partner talking points, ready to share with confidence.",
    imageUrl: null,
    illustrationKey: "chart",
    theme: "emerald",
    backgroundGradient: null,
    ctaLabel: "Know More →",
    ctaAction: "know_more",
    deepLink: "/app/feed",
    badge: "🏦 NEW ROI",
    productCategory: "ROI Update",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 86,
    sortOrder: 9,
  },
  {
    id: "hero-lender",
    contentType: "lender_announcement",
    title: "Lender Update",
    subtitle: "A newly activated lender expands your options this week.",
    imageUrl: null,
    illustrationKey: "bank",
    theme: "navy",
    backgroundGradient: null,
    ctaLabel: "View Details →",
    ctaAction: "view_details",
    deepLink: "/app/feed",
    badge: "🏦 LENDER",
    productCategory: "Lender Update",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 82,
    sortOrder: 10,
  },
  {
    id: "hero-recognition",
    contentType: "recognition",
    title: "Partner Recognition",
    subtitle: "Celebrate excellence — this month's standout performances.",
    imageUrl: null,
    illustrationKey: "recognition",
    theme: "gold",
    backgroundGradient: null,
    ctaLabel: "Explore →",
    ctaAction: "explore",
    deepLink: "/app/vgrow",
    badge: "🏆 EXCLUSIVE",
    productCategory: "Recognition",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 80,
    sortOrder: 11,
  },
  {
    id: "hero-ceo",
    contentType: "ceo_message",
    title: "CEO Message",
    subtitle: "A personal note on the quarter ahead for Wealth Partners.",
    imageUrl: null,
    illustrationKey: "ceo",
    theme: "charcoal",
    backgroundGradient: null,
    ctaLabel: "Watch Now →",
    ctaAction: "watch_now",
    deepLink: "/app/feed",
    badge: "⭐ FEATURED",
    productCategory: "Leadership",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 78,
    sortOrder: 12,
  },
  {
    id: "hero-launch",
    contentType: "product_launch",
    title: "Product Launch",
    subtitle: "Meet the newest proposition designed for your book of business.",
    imageUrl: null,
    illustrationKey: "launch",
    theme: "purple",
    backgroundGradient: null,
    ctaLabel: "Explore →",
    ctaAction: "explore",
    deepLink: "/app/marketing",
    badge: "🔥 HOT OFFER",
    productCategory: "Product Launch",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 76,
    sortOrder: 13,
  },
  {
    id: "hero-success",
    contentType: "customer_success",
    title: "Customer Success",
    subtitle: "A story worth sharing — how a partner closed with confidence.",
    imageUrl: null,
    illustrationKey: "success",
    theme: "burgundy",
    backgroundGradient: null,
    ctaLabel: "Know More →",
    ctaAction: "know_more",
    deepLink: "/app/feed",
    badge: "🎯 TARGET",
    productCategory: "Success Story",
    audience: "wealth_partners",
    publishWindow: null,
    priority: 74,
    sortOrder: 14,
  },
] as const;

export const PARTNER_HOME_BUSINESS_FEED_META = {
  title: "Business Feed",
  viewAllLabel: "View All →",
  viewAllDeepLink: "/app/feed",
} as const;

/** CO-WP-103.5 — Experience Engine Business Feed library (seed). */
export const PARTNER_HOME_FEED_CATALOG = [
  {
    id: "feed-campaign",
    contentType: "campaign",
    title: "New Campaign",
    subtitle: "Festival creatives are live for sharing with customers.",
    icon: "campaign",
    theme: "violet",
    category: "Campaign",
    publishedAt: null,
    deepLink: "/app/campaigns",
    readMoreLabel: "Read More",
    audience: "wealth_partners",
    priority: 100,
    visibilityRule: null,
  },
  {
    id: "feed-roi",
    contentType: "roi_update",
    title: "ROI Updated",
    subtitle: "Partner talking points refreshed for selected products.",
    icon: "chart",
    theme: "amber",
    category: "ROI",
    publishedAt: null,
    deepLink: "/app/feed",
    readMoreLabel: "Read More",
    audience: "wealth_partners",
    priority: 96,
    visibilityRule: null,
  },
  {
    id: "feed-product",
    contentType: "new_product",
    title: "New Product",
    subtitle: "A new proposition is ready for your customer conversations.",
    icon: "products",
    theme: "royal",
    category: "Product",
    publishedAt: null,
    deepLink: "/app/marketing",
    readMoreLabel: "Read More",
    audience: "wealth_partners",
    priority: 94,
    visibilityRule: null,
  },
  {
    id: "feed-lender",
    contentType: "new_lender",
    title: "New Lender",
    subtitle: "Expand your options with a newly activated lending partner.",
    icon: "bank",
    theme: "teal",
    category: "Lender",
    publishedAt: null,
    deepLink: "/app/feed",
    readMoreLabel: "Read More",
    audience: "wealth_partners",
    priority: 92,
    visibilityRule: null,
  },
  {
    id: "feed-contest",
    contentType: "contest",
    title: "Contest",
    subtitle: "Climb the leaderboard — rewards close soon.",
    icon: "trophy",
    theme: "crimson",
    category: "Contest",
    publishedAt: null,
    deepLink: "/app/vgrow",
    readMoreLabel: "Read More",
    audience: "wealth_partners",
    priority: 90,
    visibilityRule: null,
  },
  {
    id: "feed-creative",
    contentType: "marketing_creative",
    title: "Marketing Creative",
    subtitle: "Share-ready assets published for this week's offers.",
    icon: "gift",
    theme: "purple",
    category: "Creative",
    publishedAt: null,
    deepLink: "/app/campaigns",
    readMoreLabel: "Read More",
    audience: "wealth_partners",
    priority: 88,
    visibilityRule: null,
  },
  {
    id: "feed-training",
    contentType: "training",
    title: "Training",
    subtitle: "A short module on LAP conversations is ready.",
    icon: "book",
    theme: "emerald",
    category: "Training",
    publishedAt: null,
    deepLink: "/app/vgrow",
    readMoreLabel: "Read More",
    audience: "wealth_partners",
    priority: 86,
    visibilityRule: null,
  },
  {
    id: "feed-ceo",
    contentType: "ceo_message",
    title: "CEO Message",
    subtitle: "A personal note on the quarter ahead for Wealth Partners.",
    icon: "ceo",
    theme: "charcoal",
    category: "Leadership",
    publishedAt: null,
    deepLink: "/app/feed",
    readMoreLabel: "Read More",
    audience: "wealth_partners",
    priority: 84,
    visibilityRule: null,
  },
] as const;

export const PARTNER_HOME_HIGHLIGHTS_META = {
  title: "Today's Highlights",
} as const;

/** CO-WP-103.4 — Experience Engine Today's Highlights library (seed). */
export const PARTNER_HOME_HIGHLIGHT_CATALOG = [
  {
    id: "hl-lenders",
    title: "4 New Lenders",
    subtitle: "Fresh options to discuss today",
    icon: "bank",
    theme: "teal",
    deepLink: "/app/feed",
    badge: "Lenders",
    audience: "wealth_partners",
    priority: 100,
    visibilityRule: null,
  },
  {
    id: "hl-roi",
    title: "ROI Updated",
    subtitle: "Talking points refreshed",
    icon: "chart",
    theme: "amber",
    deepLink: "/app/feed",
    badge: "Update",
    audience: "wealth_partners",
    priority: 96,
    visibilityRule: null,
  },
  {
    id: "hl-festival",
    title: "Festival Campaign Live",
    subtitle: "Creatives ready to send",
    icon: "gift",
    theme: "violet",
    deepLink: "/app/campaigns",
    badge: "Campaign",
    audience: "wealth_partners",
    priority: 94,
    visibilityRule: null,
  },
  {
    id: "hl-contest",
    title: "Contest Ends Tomorrow",
    subtitle: "Share before the window closes",
    icon: "trophy",
    theme: "crimson",
    deepLink: "/app/vgrow",
    badge: "Contest",
    audience: "wealth_partners",
    priority: 92,
    visibilityRule: null,
  },
  {
    id: "hl-training",
    title: "New Training Available",
    subtitle: "Complete the new module",
    icon: "book",
    theme: "emerald",
    deepLink: "/app/vgrow",
    badge: "Training",
    audience: "wealth_partners",
    priority: 88,
    visibilityRule: null,
  },
] as const;

export const PARTNER_HOME_RECOMMENDED_ACTIONS_META = {
  title: "Recommended Actions",
  viewAllLabel: "View All →",
  viewAllDeepLink: "/app/tasks",
} as const;

/** CO-WP-103.3 — Experience Engine Recommended Action library (seed). */
export const PARTNER_HOME_RECOMMENDED_ACTIONS = [
  {
    id: "add_customer",
    title: "Add Customer",
    icon: "user_plus",
    theme: "emerald",
    deepLink: "/app/customers",
    audience: "wealth_partners",
    priority: 100,
    visibilityRule: null,
  },
  {
    id: "create_opportunity",
    title: "Create Opportunity",
    icon: "opportunity",
    theme: "royal",
    deepLink: "/app/opportunities/new",
    audience: "wealth_partners",
    priority: 96,
    visibilityRule: null,
  },
  {
    id: "upload_documents",
    title: "Upload Documents",
    icon: "upload",
    theme: "teal",
    deepLink: "/app/documents",
    audience: "wealth_partners",
    priority: 92,
    visibilityRule: null,
  },
  {
    id: "share_visiting_card",
    title: "Share Visiting Card",
    icon: "card",
    theme: "amber",
    deepLink: "/app/profile",
    audience: "wealth_partners",
    priority: 90,
    visibilityRule: null,
  },
  {
    id: "generate_referral_link",
    title: "Generate Referral Link",
    icon: "link",
    theme: "purple",
    deepLink: "/app/marketing",
    audience: "wealth_partners",
    priority: 88,
    visibilityRule: null,
  },
  {
    id: "business_calculator",
    title: "Business Calculator",
    icon: "calculator",
    theme: "indigo",
    deepLink: "/app/tools/business-calculator",
    audience: "wealth_partners",
    priority: 84,
    visibilityRule: null,
  },
  {
    id: "emi_calculator",
    title: "EMI Calculator",
    icon: "emi",
    theme: "crimson",
    deepLink: "/app/tools/emi-calculator",
    audience: "wealth_partners",
    priority: 82,
    visibilityRule: null,
  },
  {
    id: "training",
    title: "Training",
    icon: "book",
    theme: "teal",
    deepLink: "/app/vgrow",
    audience: "wealth_partners",
    priority: 80,
    visibilityRule: null,
  },
  {
    id: "campaigns",
    title: "Campaigns",
    icon: "campaign",
    theme: "purple",
    deepLink: "/app/campaigns",
    audience: "wealth_partners",
    priority: 78,
    visibilityRule: null,
  },
  {
    id: "products",
    title: "Products",
    icon: "products",
    theme: "royal",
    deepLink: "/app/marketing",
    audience: "wealth_partners",
    priority: 76,
    visibilityRule: null,
  },
  {
    id: "lenders",
    title: "Lenders",
    icon: "bank",
    theme: "indigo",
    deepLink: "/app/feed",
    audience: "wealth_partners",
    priority: 74,
    visibilityRule: null,
  },
] as const;

export const PARTNER_HOME_VISITING_CARD_BRANDING = {
  companyName: "Rupee Catalyst",
  brandMarkLabel: "RC",
  /**
   * Official logo path served by Wealth Partner App public assets
   * (copied from Catalyst One brand pack — do not redraw in companion).
   */
  brandMarkUrl: "/rupee-catalyst-logo-official.svg" as string | null,
} as const;

export const PARTNER_HOME_VISITING_CARD_QR = {
  status: "ready",
  imageUrl: null as string | null,
  caption: "Scan to Connect",
  payloadUrl: null as string | null,
} as const;

/** CO-WP-IDENTITY-001 — Professional Identity Card chrome (Enterprise-owned copy). */
export const PARTNER_HOME_PROFESSIONAL_IDENTITY = {
  cardTitle: "My Professional Identity",
  authorisedProductsNotice:
    "Authorised products projected for Professional Identity. Replace with Partner Entitlements engine without companion redesign.",
  verifiedIdentity: {
    status: "verified" as const,
    label: "Verified Rupee Catalyst Partner",
  },
  back: {
    scanCaption: "Scan to Connect",
    companyAddress: "Rupee Catalyst · India",
    websiteUrl: "https://rupeecatalyst.com",
    supportContact: "support@rupeecatalyst.com",
    corporateDisclaimer:
      "This Professional Identity Card identifies an authorised Wealth Partner representing Rupee Catalyst. Verify credentials through official Rupee Catalyst channels.",
    poweredByLabel: "Powered by Rupee Catalyst",
  },
  futurePlaceholders: [
    { id: "certifications", label: "Certifications", status: "reserved" as const },
    { id: "awards", label: "Awards", status: "reserved" as const },
    { id: "social_links", label: "Social Links", status: "reserved" as const },
    { id: "calendar_booking", label: "Calendar Booking", status: "reserved" as const },
    { id: "branch_details", label: "Branch Details", status: "reserved" as const },
    { id: "digital_signature", label: "Digital Signature", status: "reserved" as const },
  ],
} as const;

/**
 * CO-WP-IDENTITY-001 — Product authorisation projection seed.
 * Temporary Enterprise projection until Partner Entitlements engine is authorised.
 * Companion must render this list only — never hardcode products.
 */
export const PARTNER_HOME_IDENTITY_PRODUCT_AUTHORISATIONS = [
  { productCode: "HOME_LOAN", productLabel: "Home Loan", iconLabel: "HL" },
  { productCode: "LAP", productLabel: "Loan Against Property", iconLabel: "LP" },
  { productCode: "BUSINESS_LOAN_UNSECURED", productLabel: "Business Loan", iconLabel: "BL" },
  { productCode: "MUTUAL_FUNDS", productLabel: "Mutual Funds", iconLabel: "MF" },
  { productCode: "INSURANCE", productLabel: "Insurance", iconLabel: "IN" },
  { productCode: "FIXED_DEPOSITS", productLabel: "Fixed Deposits", iconLabel: "FD" },
] as const;

/** Default tier projection until Partner Tier Engine is authorised. */
export const PARTNER_HOME_IDENTITY_DEFAULT_TIER = {
  tierCode: "gold",
  tierLabel: "Gold",
} as const;

/** CO-WP-103.6 / CO-WP-IDENTITY-001 / Catalyst Connect §7 — Identity quick actions. */
export const PARTNER_HOME_VISITING_CARD_ACTIONS = [
  {
    id: "share",
    label: "Share",
    icon: "share",
    deepLink: "/app/identity",
    audience: "wealth_partners",
    priority: 50,
    sortOrder: 0,
    visibilityRule: null,
    schedule: null,
    personalisationKey: null,
  },
  {
    id: "whatsapp",
    label: "WhatsApp",
    icon: "whatsapp",
    deepLink: "/app/identity",
    audience: "wealth_partners",
    priority: 40,
    sortOrder: 1,
    visibilityRule: null,
    schedule: null,
    personalisationKey: null,
  },
  {
    id: "copy_link",
    label: "Copy Link",
    icon: "share",
    deepLink: "/app/identity",
    audience: "wealth_partners",
    priority: 30,
    sortOrder: 2,
    visibilityRule: null,
    schedule: null,
    personalisationKey: null,
  },
  {
    id: "save_qr",
    label: "Save QR",
    icon: "download",
    deepLink: "/app/identity",
    audience: "wealth_partners",
    priority: 20,
    sortOrder: 3,
    visibilityRule: null,
    schedule: null,
    personalisationKey: null,
  },
  {
    id: "preview_public",
    label: "Preview",
    icon: "share",
    deepLink: "/app/identity",
    audience: "wealth_partners",
    priority: 10,
    sortOrder: 4,
    visibilityRule: null,
    schedule: null,
    personalisationKey: null,
  },
  {
    id: "call",
    label: "Call",
    icon: "call",
    deepLink: "/app/identity",
    audience: "wealth_partners",
    priority: 5,
    sortOrder: 5,
    visibilityRule: null,
    schedule: null,
    personalisationKey: null,
  },
  {
    id: "email",
    label: "Email",
    icon: "email",
    deepLink: "/app/identity",
    audience: "wealth_partners",
    priority: 4,
    sortOrder: 6,
    visibilityRule: null,
    schedule: null,
    personalisationKey: null,
  },
] as const;

/** CO-WP-103.11 — Notification Experience (Experience Engine seed). */
export const PARTNER_HOME_NOTIFICATIONS_META = {
  title: "Notifications",
  markReadLabel: "Mark read",
  markAllReadLabel: "Mark all read",
  emptyTitle: "You're all caught up",
  emptySubtitle: "Enterprise will deliver new alerts here.",
  categories: [
    { id: "business", label: "Business", emoji: "🏦" },
    { id: "campaigns", label: "Campaigns", emoji: "🎁" },
    { id: "training", label: "Training", emoji: "📚" },
    { id: "announcements", label: "Announcements", emoji: "📢" },
    { id: "saarthi", label: "Saarthi", emoji: "💬" },
    { id: "customers", label: "Customers", emoji: "👤" },
  ],
} as const;

export const PARTNER_HOME_NOTIFICATION_CATALOG = [
  {
    id: "notif-biz-followup",
    category: "business",
    icon: "phone",
    title: "Follow-up due today",
    subtitle: "Two customer callbacks are waiting in your queue.",
    publishedAt: null as string | null,
    priority: "high",
    read: false,
    deepLink: "/app/tasks",
    theme: "teal",
    sortOrder: 10,
  },
  {
    id: "notif-biz-docs",
    category: "business",
    icon: "upload",
    title: "Documents pending review",
    subtitle: "A loan file needs supporting papers before login.",
    publishedAt: null as string | null,
    priority: "normal",
    read: false,
    deepLink: "/app/documents",
    theme: "amber",
    sortOrder: 20,
  },
  {
    id: "notif-camp-festive",
    category: "campaigns",
    icon: "gift",
    title: "Festive campaign live",
    subtitle: "Share the new Wealth Partner festive kit with customers.",
    publishedAt: null as string | null,
    priority: "normal",
    read: false,
    deepLink: "/app/campaigns",
    theme: "gold",
    sortOrder: 30,
  },
  {
    id: "notif-train-module",
    category: "training",
    icon: "book",
    title: "New training module",
    subtitle: "Complete ‘Product Suitability Basics’ this week.",
    publishedAt: null as string | null,
    priority: "normal",
    read: true,
    deepLink: "/app/vgrow",
    theme: "indigo",
    sortOrder: 40,
  },
  {
    id: "notif-ann-policy",
    category: "announcements",
    icon: "campaign",
    title: "Policy update",
    subtitle: "Enterprise published a short note on partner compliance.",
    publishedAt: null as string | null,
    priority: "high",
    read: false,
    deepLink: "/app/feed",
    theme: "navy",
    sortOrder: 50,
  },
  {
    id: "notif-saarthi-tip",
    category: "saarthi",
    icon: "opportunity",
    title: "Saarthi tip ready",
    subtitle: "Ask Saarthi how to prep for today’s customer meetings.",
    publishedAt: null as string | null,
    priority: "low",
    read: true,
    deepLink: "/app/saarthi",
    theme: "mint",
    sortOrder: 60,
  },
  {
    id: "notif-cust-birthday",
    category: "customers",
    icon: "ceo",
    title: "Customer birthday tomorrow",
    subtitle: "Send a warm note — relationship moments convert.",
    publishedAt: null as string | null,
    priority: "normal",
    read: false,
    deepLink: "/app/customers",
    theme: "rose",
    sortOrder: 70,
  },
  {
    id: "notif-cust-reply",
    category: "customers",
    icon: "reply",
    title: "Customer replied",
    subtitle: "A WhatsApp reply is waiting in Dialogue.",
    publishedAt: null as string | null,
    priority: "critical",
    read: false,
    deepLink: "/app/dialogue",
    theme: "crimson",
    sortOrder: 5,
  },
] as const;

/** CO-WP-103.12 — Global Search (Experience Engine seed · presentation only). */
export const PARTNER_HOME_GLOBAL_SEARCH_META = {
  title: "Search",
  placeholder: "Search customers, products, campaigns…",
  recentTitle: "Recent Searches",
  quickTitle: "Quick Suggestions",
  suggestionsTitle: "Suggestions",
  scopesTitle: "Browse",
  emptyTitle: "Nothing matches yet",
  emptySubtitle: "Try another word — Enterprise search arrives soon.",
  clearRecentLabel: "Clear",
  triggerLabel: "Search anything",
  scopes: [
    { id: "customers", label: "Customers", icon: "ceo", theme: "teal" },
    { id: "loan_files", label: "Loan Files", icon: "opportunity", theme: "navy" },
    { id: "products", label: "Products", icon: "products", theme: "gold" },
    { id: "lenders", label: "Lenders", icon: "bank", theme: "indigo" },
    { id: "training", label: "Training", icon: "book", theme: "mint" },
    { id: "campaigns", label: "Campaigns", icon: "gift", theme: "rose" },
    { id: "documents", label: "Documents", icon: "upload", theme: "amber" },
    { id: "knowledge_base", label: "Knowledge Base", icon: "book", theme: "charcoal" },
    { id: "saarthi", label: "Saarthi", icon: "opportunity", theme: "teal" },
  ],
} as const;

export const PARTNER_HOME_RECENT_SEARCHES = [
  {
    id: "recent-home-loan",
    label: "Home Loan",
    scope: "products",
    deepLink: "/app/opportunities",
  },
  {
    id: "recent-campaign",
    label: "Festive campaign",
    scope: "campaigns",
    deepLink: "/app/campaigns",
  },
  {
    id: "recent-customer",
    label: "Priya Sharma",
    scope: "customers",
    deepLink: "/app/customers",
  },
] as const;

export const PARTNER_HOME_QUICK_SUGGESTIONS = [
  {
    id: "quick-customers",
    label: "Find a customer",
    icon: "ceo",
    theme: "teal",
    scope: "customers",
    deepLink: "/app/customers",
  },
  {
    id: "quick-products",
    label: "Browse products",
    icon: "products",
    theme: "gold",
    scope: "products",
    deepLink: "/app/opportunities",
  },
  {
    id: "quick-campaigns",
    label: "Open campaigns",
    icon: "gift",
    theme: "rose",
    scope: "campaigns",
    deepLink: "/app/campaigns",
  },
  {
    id: "quick-training",
    label: "Start training",
    icon: "book",
    theme: "mint",
    scope: "training",
    deepLink: "/app/vgrow",
  },
  {
    id: "quick-saarthi",
    label: "Ask Saarthi",
    icon: "opportunity",
    theme: "teal",
    scope: "saarthi",
    deepLink: "/app/saarthi",
  },
  {
    id: "quick-docs",
    label: "Documents",
    icon: "upload",
    theme: "amber",
    scope: "documents",
    deepLink: "/app/documents",
  },
] as const;

export const PARTNER_HOME_SEARCH_SUGGESTIONS = [
  {
    id: "sug-cust-priya",
    scope: "customers",
    title: "Priya Sharma",
    subtitle: "Customer · Mumbai · Active relationship",
    icon: "ceo",
    theme: "teal",
    deepLink: "/app/customers",
    keywords: ["priya", "sharma", "customer", "mumbai"],
    priority: 100,
    sortOrder: 10,
  },
  {
    id: "sug-loan-hl-12",
    scope: "loan_files",
    title: "HL-2026-0142",
    subtitle: "Loan File · Home Loan · Under process",
    icon: "opportunity",
    theme: "navy",
    deepLink: "/app/opportunities",
    keywords: ["loan", "home loan", "hl", "file"],
    priority: 96,
    sortOrder: 20,
  },
  {
    id: "sug-prod-home",
    scope: "products",
    title: "Home Loan",
    subtitle: "Product · Secured lending · Partner kit ready",
    icon: "products",
    theme: "gold",
    deepLink: "/app/opportunities",
    keywords: ["home", "loan", "product", "hl"],
    priority: 94,
    sortOrder: 30,
  },
  {
    id: "sug-lender-hdfc",
    scope: "lenders",
    title: "HDFC Bank",
    subtitle: "Lender · Housing · Preferred partner",
    icon: "bank",
    theme: "indigo",
    deepLink: "/app/business",
    keywords: ["hdfc", "bank", "lender", "housing"],
    priority: 90,
    sortOrder: 40,
  },
  {
    id: "sug-train-suitability",
    scope: "training",
    title: "Product Suitability Basics",
    subtitle: "Training · 18 min · Recommended this week",
    icon: "book",
    theme: "mint",
    deepLink: "/app/vgrow",
    keywords: ["training", "suitability", "product", "learn"],
    priority: 88,
    sortOrder: 50,
  },
  {
    id: "sug-camp-festive",
    scope: "campaigns",
    title: "Festive Wealth Campaign",
    subtitle: "Campaign · Share kit · WhatsApp ready",
    icon: "gift",
    theme: "rose",
    deepLink: "/app/campaigns",
    keywords: ["festive", "campaign", "wealth", "kit"],
    priority: 92,
    sortOrder: 60,
  },
  {
    id: "sug-doc-checklist",
    scope: "documents",
    title: "KYC document checklist",
    subtitle: "Documents · Partner reference pack",
    icon: "upload",
    theme: "amber",
    deepLink: "/app/documents",
    keywords: ["kyc", "documents", "checklist", "papers"],
    priority: 84,
    sortOrder: 70,
  },
  {
    id: "sug-kb-bt",
    scope: "knowledge_base",
    title: "Balance Transfer playbook",
    subtitle: "Knowledge Base · How to position BT deals",
    icon: "book",
    theme: "charcoal",
    deepLink: "/app/feed",
    keywords: ["balance", "transfer", "bt", "knowledge", "playbook"],
    priority: 82,
    sortOrder: 80,
  },
  {
    id: "sug-saarthi-meeting",
    scope: "saarthi",
    title: "Prep my customer meeting",
    subtitle: "Saarthi · Guidance prompt",
    icon: "opportunity",
    theme: "teal",
    deepLink: "/app/saarthi",
    keywords: ["saarthi", "meeting", "prep", "ask", "help"],
    priority: 86,
    sortOrder: 90,
  },
] as const;

/**
 * CO-WP-103.13 — Home Personalisation (Experience Engine seed).
 * Tokens `{givenName}`, `{salutation}`, `{partnerDisplayName}` are resolved
 * by Partner Home projection — companion never invents copy.
 */
export const PARTNER_HOME_PERSONALISATION_META = {
  title: "For You",
  emptyTitle: "Personal moments arrive soon",
  emptySubtitle: "Enterprise Experience Engine will curate this space.",
} as const;

export const PARTNER_HOME_PERSONALISATION_CATALOG = [
  {
    id: "pers-time-greeting",
    kind: "time_greeting",
    eyebrow: "Greeting",
    title: "{salutation}, {givenName}",
    body: "Your day is ready — open with clarity and confidence.",
    icon: "opportunity",
    theme: "teal",
    deepLink: null as string | null,
    ctaLabel: null as string | null,
    priority: 100,
    sortOrder: 10,
  },
  {
    id: "pers-welcome-back",
    kind: "welcome_back",
    eyebrow: "Welcome Back",
    title: "Welcome back, {givenName}",
    body: "Pick up where you left off — customers and campaigns await.",
    icon: "ceo",
    theme: "navy",
    deepLink: "/app/home",
    ctaLabel: null as string | null,
    priority: 96,
    sortOrder: 20,
  },
  {
    id: "pers-birthday",
    kind: "birthday",
    eyebrow: "Happy Birthday",
    title: "Happy Birthday, {givenName}",
    body: "Celebrating you today — may this year bring growth and joy.",
    icon: "gift",
    theme: "rose",
    deepLink: null as string | null,
    ctaLabel: null as string | null,
    priority: 94,
    sortOrder: 30,
  },
  {
    id: "pers-congrats",
    kind: "congratulations",
    eyebrow: "Congratulations",
    title: "Well done, {givenName}",
    body: "A milestone moment — keep the momentum going this week.",
    icon: "trophy",
    theme: "gold",
    deepLink: "/app/vgrow",
    ctaLabel: "View progress",
    priority: 90,
    sortOrder: 40,
  },
  {
    id: "pers-motivation",
    kind: "motivation",
    eyebrow: "Today's Motivation",
    title: "Consistency compounds",
    body: "One thoughtful conversation today can shape a lifetime customer.",
    icon: "target",
    theme: "mint",
    deepLink: null as string | null,
    ctaLabel: null as string | null,
    priority: 86,
    sortOrder: 50,
  },
  {
    id: "pers-festival",
    kind: "festival",
    eyebrow: "Festival Greetings",
    title: "Season's warmth to you, {givenName}",
    body: "Celebrate with gratitude — share festive cheer with your customers.",
    icon: "gift",
    theme: "amber",
    deepLink: "/app/campaigns",
    ctaLabel: "Open campaigns",
    priority: 84,
    sortOrder: 60,
  },
  {
    id: "pers-quote",
    kind: "business_quote",
    eyebrow: "Today's Business Quote",
    title: "Trust is the real currency",
    body: "Protect every promise — reputation travels faster than any campaign.",
    icon: "book",
    theme: "charcoal",
    deepLink: null as string | null,
    ctaLabel: null as string | null,
    priority: 80,
    sortOrder: 70,
  },
] as const;
