export {
  applyEafBasePatch,
  bumpEafAssetVersion,
  compareEafVersions,
  createEafAssetDraft,
  createEafExtendedAssetDraft,
  createEafRelationship,
  createEafVersionRecord,
  createEafVersionedEvent,
  deactivateEafRelationship,
  formatEafVersion,
  getAllowedEafLifecycleTargets,
  getCurrentEafVersionRecord,
  getEafAssetById,
  getEafAssetDefinition,
  getEafAssetGraph,
  getEafAssetHealth,
  getEafAssetTypeDefinition,
  getEafAssetTypeDefinitions,
  getEafAssets,
  getEafAuditTrail,
  getEafAuditTrailForAsset,
  getEafCapabilitiesForAssetType,
  getEafConfigurationProvider,
  getEafFrameworkSnapshot,
  getEafFrameworkVersion,
  getEafLifecycleDefinitionById,
  getEafLifecycleDefinitions,
  getEafLifecycleForAssetType,
  getEafMetadataHooks,
  getEafPermissionHooks,
  getEafRegistryEntry,
  getEafRelationshipTypeDefinitions,
  getEafRelationshipsForAsset,
  getEafVersionRecords,
  listEafAssetDefinitions,
  listEafAssetManifests,
  listEafCapabilityDefinitions,
  listEafEngineRegistrations,
  parseEafVersion,
  registerEafAsset,
  registerEafAssetTypeDefinition,
  registerEafCapabilityDefinition,
  registerEafDynamicField,
  registerEafEngine,
  registerEafFeatureFlagHook,
  registerEafLifecycleDefinition,
  registerEafRelationshipTypeDefinition,
  resetEafAuditTrail,
  resetEafComposition,
  resetEafHookRegistries,
  resetEafRegistry,
  resetEafRelationships,
  searchEafRegistry,
  transitionEafLifecycle,
  updateEafAsset,
  wrapEafDomainEvent,
  buildEafAssetManifest,
  assessEafAssetHealth,
} from "@/lib/enterprise-asset-framework";

export {
  EAF_ASSET_HEALTH_STATUS,
  EAF_ASSET_HEALTH_STATUS_LABELS,
  EAF_AUDIT_ACTION_LABELS,
  EAF_AUDIT_ACTIONS,
  EAF_CAPABILITY_CODES,
  EAF_DEFAULT_ASSET_TYPE_DEFINITIONS,
  EAF_DEFAULT_CAPABILITY_DEFINITIONS,
  EAF_DEFAULT_LIFECYCLE_CODE,
  EAF_DEFAULT_LIFECYCLE_DEFINITION,
  EAF_DEFAULT_RELATIONSHIP_TYPES,
  EAF_ENGINE_CODES,
  EAF_EVENT_NAMES,
  EAF_EVENT_SCHEMA_VERSION,
  EAF_EVENT_VERSIONS,
  EAF_EXTENSION_POINT_CODES,
  EAF_FRAMEWORK_HARDENING_VERSION,
  EAF_FRAMEWORK_VERSION,
  EAF_LIFECYCLE_STATE_CODES,
  EAF_LIFECYCLE_STATE_LABELS,
  EAF_RELATIONSHIP_TYPE_CODES,
  canTransitionEafLifecycle,
  getEafLifecycleStateOrder,
  getEafLifecycleTransitionsFrom,
  isEafLifecycleTerminal,
} from "@/constants/enterprise-asset-framework";

export type {
  EafAiHookDefinition,
  EafAiMetadata,
  EafAssetRegistryEntry,
  EafAssetRelationship,
  EafAssetTypeDefinition,
  EafAssetVersionRecord,
  EafAuditAction,
  EafAuditEntry,
  EafBaseAsset,
  EafDynamicFieldDefinition,
  EafDynamicFormDefinition,
  EafDynamicLayoutDefinition,
  EafExtendedAsset,
  EafFrameworkRegistrySnapshot,
  EafLifecycleDefinition,
  EafMetadataHookBundle,
  EafPermissionHookBundle,
  EafRelationshipTypeDefinition,
  EafRolePermissionHook,
  EafSearchMetadata,
  EafValidationRuleDefinition,
  EafVisibilityRuleHook,
  EafWorkspaceProfileHook,
} from "@/types/enterprise-asset-framework";

export type {
  EafAssetCapabilityDeclaration,
  EafCapabilityDefinition,
} from "@/types/enterprise-asset-framework-capabilities";

export type {
  EafAssetDefinition,
  EafAssetHealthRecord,
  EafAssetHealthStatus,
  EafAssetManifest,
  EafCompatibilityInfo,
} from "@/types/enterprise-asset-framework-definition";

export type {
  EafEngineRegistration,
} from "@/types/enterprise-asset-framework-engines";

export type {
  EafDomainEvent,
  EafVersionedEventEnvelope,
} from "@/types/enterprise-asset-framework-events";

export type {
  EafAssetFeatureFlagState,
  EafFeatureFlagHook,
} from "@/types/enterprise-asset-framework-feature-flags";
