/**
 * CO-C1-CHART-READABILITY-001 — Catalogue of current Catalyst One chart surfaces.
 * Used by the verifier; keep in sync when adding dashboards.
 */

export const ENTERPRISE_CHART_INVENTORY = [
  {
    id: "exec-source-mix",
    title: "Opportunity Source Mix",
    component: "DashboardDoughnutChart",
    path: "src/components/catalyst-one/user-home-dashboard/charts/dashboard-doughnut-chart.tsx",
    dashboard: "Executive Dashboard / Visual Analytics",
    kind: "doughnut",
    dataSource: "Dashboard visual analytics snapshot (Opportunity Registry)",
  },
  {
    id: "exec-product-mix",
    title: "Product Mix",
    component: "EiTreemapChart",
    path: "src/components/catalyst-one/executive-intelligence/viz/ei-treemap-chart.tsx",
    dashboard: "Executive Dashboard / Visual Analytics",
    kind: "treemap",
    dataSource: "Dashboard visual analytics snapshot",
  },
  {
    id: "exec-stage-distribution",
    title: "Opportunity Stage Distribution",
    component: "DashboardDoughnutChart",
    path: "src/components/catalyst-one/user-home-dashboard/charts/dashboard-doughnut-chart.tsx",
    dashboard: "Executive Dashboard / Visual Analytics",
    kind: "doughnut",
    dataSource: "Dashboard visual analytics snapshot",
  },
  {
    id: "exec-monthly-trend",
    title: "Monthly Trend",
    component: "DashboardTrendLineChart",
    path: "src/components/catalyst-one/user-home-dashboard/charts/dashboard-bar-charts.tsx",
    dashboard: "Executive Dashboard / Visual Analytics",
    kind: "line",
    dataSource: "Dashboard visual analytics snapshot",
  },
  {
    id: "exec-lender-distribution",
    title: "Lender Distribution",
    component: "DashboardHorizontalBarChart",
    path: "src/components/catalyst-one/user-home-dashboard/charts/dashboard-bar-charts.tsx",
    dashboard: "Executive Dashboard / Visual Analytics",
    kind: "bar",
    dataSource: "Dashboard visual analytics snapshot",
  },
  {
    id: "exec-ageing",
    title: "Opportunity Ageing",
    component: "DashboardAgeingStackedBar",
    path: "src/components/catalyst-one/user-home-dashboard/charts/dashboard-bar-charts.tsx",
    dashboard: "Executive Dashboard / Visual Analytics",
    kind: "bar",
    dataSource: "Dashboard visual analytics snapshot",
  },
  {
    id: "exec-task-analytics",
    title: "Task Analytics",
    component: "DashboardDoughnutChart",
    path: "src/components/catalyst-one/user-home-dashboard/charts/dashboard-doughnut-chart.tsx",
    dashboard: "Executive Dashboard / Visual Analytics",
    kind: "doughnut",
    dataSource: "Dashboard visual analytics snapshot / ETE",
  },
  {
    id: "exec-disbursement",
    title: "Disbursement Analytics",
    component: "DashboardDisbursementBarChart",
    path: "src/components/catalyst-one/user-home-dashboard/charts/dashboard-bar-charts.tsx",
    dashboard: "Executive Dashboard / Visual Analytics",
    kind: "bar",
    dataSource: "Dashboard visual analytics snapshot",
  },
  {
    id: "exec-revenue-trajectory",
    title: "Revenue / Disbursement trajectory",
    component: "DashboardChartsRow",
    path: "src/components/catalyst-one/dashboard/dashboard-charts-row.tsx",
    dashboard: "Executive Dashboard",
    kind: "line",
    dataSource: "Persona dashboard series (filtered; not invented for empty states)",
  },
  {
    id: "exec-login-trend",
    title: "Login Trend",
    component: "LoginTrendChart",
    path: "src/components/catalyst-one/dashboard/login-trend-chart.tsx",
    dashboard: "Executive Dashboard",
    kind: "line",
    dataSource: "Dashboard login trend series",
  },
  {
    id: "exec-lead-arrival",
    title: "Lead Arrival Trend",
    component: "LeadArrivalChart",
    path: "src/components/catalyst-one/dashboard/lead-arrival-chart.tsx",
    dashboard: "Executive Dashboard",
    kind: "line",
    dataSource: "Dashboard lead arrival series",
  },
  {
    id: "exec-target-gauges",
    title: "Target Achievement",
    component: "TargetGaugeGrid",
    path: "src/components/catalyst-one/dashboard/target-gauge-grid.tsx",
    dashboard: "Executive Dashboard",
    kind: "gauge",
    dataSource: "Dashboard target gauges",
  },
  {
    id: "mc-revenue",
    title: "Revenue Analytics (waterfall, trend, mix, realisation)",
    component: "RevenueAnalyticsWorkspace",
    path: "src/mission-control/revenue-analytics/RevenueAnalyticsWorkspace.tsx",
    dashboard: "Revenue Analytics / Accounting read-only analytics",
    kind: "waterfall",
    dataSource: "Accounting invoices + payments + EBI snapshot (no fabricated revenue)",
  },
  {
    id: "mc-ei-platform",
    title: "Enterprise Intelligence sections",
    component: "EnterpriseIntelligencePlatform",
    path: "src/mission-control/enterprise-intelligence/EnterpriseIntelligencePlatform.tsx",
    dashboard: "Enterprise Intelligence",
    kind: "bar",
    dataSource: "Precomputed Mission Control EI pack",
  },
  {
    id: "mc-ops",
    title: "Operations Intelligence (funnel, treemap, radar)",
    component: "OperationsIntelligenceWorkspace",
    path: "src/components/catalyst-one/operations-intelligence/operations-intelligence-workspace.tsx",
    dashboard: "Operations Intelligence",
    kind: "funnel",
    dataSource: "Certified EBI snapshot",
  },
  {
    id: "mc-situation-room",
    title: "Situation Room",
    component: "SituationRoom (KPI/list — no Recharts)",
    path: "src/mission-control/situation-room",
    dashboard: "Situation Room",
    kind: "kpi",
    dataSource: "Mission Control snapshot — no cartesian charts invented",
  },
  {
    id: "ei-story",
    title: "Executive Intelligence story chapters",
    component: "EiVizShell / EiCapableChapter",
    path: "src/components/catalyst-one/executive-intelligence/ei-viz-shell.tsx",
    dashboard: "Enterprise Intelligence / CHANAKYA Radar analytics",
    kind: "funnel",
    dataSource: "deriveExecutiveIntelligenceStory",
  },
  {
    id: "relationship-heat-map",
    title: "Relationship Heat Map",
    component: "RelationshipHeatMap",
    path: "src/mission-control/relationship-heat-map/RelationshipHeatMap.tsx",
    dashboard: "Relationship Heat Map",
    kind: "heatmap",
    dataSource: "ECM contacts + EAR meaningful interactions",
  },
  {
    id: "exec-target-panel",
    title: "Target Achievement (panel)",
    component: "TargetAchievementPanel",
    path: "src/components/catalyst-one/dashboard/target-achievement-panel.tsx",
    dashboard: "Executive Dashboard",
    kind: "gauge",
    dataSource: "Dashboard target gauges",
  },
  {
    id: "lp-dashboard",
    title: "Lending Programs dashboard charts",
    component: "LpDashboardCharts",
    path: "src/components/catalyst-one/lending-programs-workspace/lp-dashboard-charts.tsx",
    dashboard: "Lending Programs",
    kind: "doughnut",
    dataSource: "Lending program workspace facts",
  },
  {
    id: "relationship-portfolio",
    title: "Relationship Portfolio",
    component: "RelationshipPortfolioSection",
    path: "src/components/catalyst-one/customers/relationship-portfolio-section.tsx",
    dashboard: "Contact 360",
    kind: "doughnut",
    dataSource: "Disbursed relationship value by product",
  },
  {
    id: "exec-briefing-performance",
    title: "Business Performance",
    component: "BusinessPerformanceSection",
    path: "src/mission-control/executive-briefing/components/BusinessPerformanceSection.tsx",
    dashboard: "Executive Briefing",
    kind: "bar",
    dataSource: "Executive briefing model",
  },
] as const;
