export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  CUSTOMERS: "/customers",
  LOAN_FILES: "/loan-files",
  PIPELINE: "/pipeline",
  LENDERS: "/lenders",
  DOCUMENTS: "/documents",
  TASKS: "/tasks",
  ACCOUNTING: "/accounting",
  REPORTS: "/reports",
  AI_ASSISTANT: "/ai-assistant",
  SETTINGS: "/settings",
  DESIGN_SYSTEM: "/design-system",
  ORGANIZATION: "/organization",
  ORGANIZATION_COMPANY_PROFILE: "/organization/company-profile",
  ORGANIZATION_DIRECTORS: "/organization/directors",
  ORGANIZATION_CORPORATE_REPOSITORY: "/organization/corporate-repository",
  ORGANIZATION_BANK_ACCOUNTS: "/organization/bank-accounts",
  ORGANIZATION_DIGITAL_SIGNATURES: "/organization/digital-signatures",
  ORGANIZATION_COMPANY_SEAL: "/organization/company-seal",
} as const;

export const PUBLIC_ROUTES = [
  ROUTES.LOGIN,
  ROUTES.FORGOT_PASSWORD,
  ROUTES.RESET_PASSWORD,
] as const;

export const AUTH_ROUTES = [
  ROUTES.LOGIN,
  ROUTES.FORGOT_PASSWORD,
  ROUTES.RESET_PASSWORD,
] as const;

export const PROTECTED_ROUTES = [
  ROUTES.DASHBOARD,
  ROUTES.CUSTOMERS,
  ROUTES.LOAN_FILES,
  ROUTES.PIPELINE,
  ROUTES.LENDERS,
  ROUTES.DOCUMENTS,
  ROUTES.TASKS,
  ROUTES.ACCOUNTING,
  ROUTES.REPORTS,
  ROUTES.AI_ASSISTANT,
  ROUTES.SETTINGS,
  ROUTES.DESIGN_SYSTEM,
  ROUTES.ORGANIZATION,
  ROUTES.ORGANIZATION_COMPANY_PROFILE,
  ROUTES.ORGANIZATION_DIRECTORS,
  ROUTES.ORGANIZATION_CORPORATE_REPOSITORY,
  ROUTES.ORGANIZATION_BANK_ACCOUNTS,
  ROUTES.ORGANIZATION_DIGITAL_SIGNATURES,
  ROUTES.ORGANIZATION_COMPANY_SEAL,
] as const;
