import { ROUTES } from "@/constants/routes";

/** UX-01B — Logical close destinations for Catalyst One workspaces. */
export const WORKSPACE_CLOSE = {
  DASHBOARD: ROUTES.DASHBOARD,
  CUSTOMERS: ROUTES.CUSTOMERS,
  LOAN_FILES: ROUTES.LOAN_FILES,
  PIPELINE: ROUTES.CHANAKYA_RADAR,
  CREDIT_RISK_ENGINE: ROUTES.ADMIN_CREDIT_RISK_ENGINE,
  PRODUCT_LIBRARY: ROUTES.ADMIN_PRODUCT_LIBRARY,
  PRODUCT_REGISTRY: ROUTES.ADMIN_PRODUCT_REGISTRY,
  RULE_LIBRARY: ROUTES.ADMIN_CREDIT_RISK_RULE_LIBRARY,
  POLICY_LIBRARY: ROUTES.ADMIN_CREDIT_RISK_POLICY_LIBRARY,
  ENTERPRISE_ASSETS: ROUTES.ADMIN_ENTERPRISE_ASSETS,
  ENTERPRISE_ASSET_REGISTRY: ROUTES.ADMIN_ENTERPRISE_ASSETS_REGISTRY,
} as const;
