/**
 * Machine-readable Match % fail-closed reasons.
 * These are criterion outcomes, not a second scoring catalogue.
 */
export const MATCH_PERCENT_CRITERION_REASONS = {
  ROI_SCORING_CONTRACT_PENDING: "ROI_SCORING_CONTRACT_PENDING",
  FOIR_SCORING_CONTRACT_PENDING: "FOIR_SCORING_CONTRACT_PENDING",
  FOIR_ABOVE_NORM_SCORING_CONTRACT_PENDING: "FOIR_ABOVE_NORM_SCORING_CONTRACT_PENDING",
  LTV_SCORING_CONTRACT_PENDING: "LTV_SCORING_CONTRACT_PENDING",
  APPLICABLE_ROI_UNAVAILABLE: "APPLICABLE_ROI_UNAVAILABLE",
} as const;

export type MatchPercentCriterionReason =
  (typeof MATCH_PERCENT_CRITERION_REASONS)[keyof typeof MATCH_PERCENT_CRITERION_REASONS];
