/**
 * EOLE lifecycle and framework constants.
 */

export const EOLE_FRAMEWORK_VERSION = "13.0.0";

export const EOLE_OPPORTUNITY_LIFECYCLE_STATUS = {
  NEW: "new",
  DOCUMENTS_PENDING: "documents_pending",
  PROCESSING: "processing",
  LENDER_REVIEW: "lender_review",
  APPROVED: "approved",
  PARTIALLY_DISBURSED: "partially_disbursed",
  FULLY_DISBURSED: "fully_disbursed",
  REJECTED: "rejected",
  CANCELLED: "cancelled",
  EXPIRED: "expired",
  ARCHIVED: "archived",
  ON_HOLD: "on_hold",
} as const;

export const EOLE_ACTIVE_LIFECYCLE_STATUSES = [
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.NEW,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.DOCUMENTS_PENDING,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PROCESSING,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.LENDER_REVIEW,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.APPROVED,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PARTIALLY_DISBURSED,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD,
] as const;

export const EOLE_TERMINAL_LIFECYCLE_STATUSES = [
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.FULLY_DISBURSED,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.REJECTED,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.EXPIRED,
  EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ARCHIVED,
] as const;

export const EOLE_BUSINESS_MODELS = {
  SECURED_LENDING: "secured_lending",
  UNSECURED_LENDING: "unsecured_lending",
} as const;

export const EOLE_PIPELINE_STATUS = {
  ACTIVE: "active",
  COMPLETED: "completed",
  FAILED: "failed",
  WITHDRAWN: "withdrawn",
} as const;

export const EOLE_LENDER_PIPELINE_OUTCOME = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  DISBURSED: "disbursed",
  WITHDRAWN: "withdrawn",
} as const;

export const EOLE_HOLD_STATUS = {
  ACTIVE: "active",
  RESUMED: "resumed",
  EXPIRED: "expired",
  CLOSED: "closed",
} as const;

export const EOLE_OWNER_TYPES = {
  SOURCE_OWNER: "source_owner",
  RELATIONSHIP_MANAGER: "relationship_manager",
  PARTNER: "partner",
  INTERNAL_TEAM: "internal_team",
} as const;

export const EOLE_EXECUTOR_ROLES = {
  PRIMARY_EXECUTOR: "primary_executor",
  SECONDARY_EXECUTOR: "secondary_executor",
  LENDER_COORDINATOR: "lender_coordinator",
  DOCUMENT_COORDINATOR: "document_coordinator",
} as const;

export const EOLE_OPPORTUNITY_LIFECYCLE_TRANSITIONS: Record<string, string[]> = {
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.NEW]: [
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.DOCUMENTS_PENDING,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD,
  ],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.DOCUMENTS_PENDING]: [
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PROCESSING,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD,
  ],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PROCESSING]: [
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.LENDER_REVIEW,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD,
  ],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.LENDER_REVIEW]: [
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.APPROVED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.REJECTED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD,
  ],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.APPROVED]: [
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PARTIALLY_DISBURSED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.FULLY_DISBURSED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD,
  ],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PARTIALLY_DISBURSED]: [
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.FULLY_DISBURSED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD,
  ],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD]: [
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PROCESSING,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.LENDER_REVIEW,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.APPROVED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED,
    EOLE_OPPORTUNITY_LIFECYCLE_STATUS.EXPIRED,
  ],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.FULLY_DISBURSED]: [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ARCHIVED],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.REJECTED]: [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ARCHIVED],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED]: [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ARCHIVED],
  [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.EXPIRED]: [EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ARCHIVED],
};

export const EOLE_OPPORTUNITY_LIFECYCLE_ACTION_MAP: Record<string, string> = {
  submit_documents: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.DOCUMENTS_PENDING,
  begin_processing: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PROCESSING,
  submit_to_lender: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.LENDER_REVIEW,
  approve: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.APPROVED,
  reject: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.REJECTED,
  partial_disburse: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.PARTIALLY_DISBURSED,
  full_disburse: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.FULLY_DISBURSED,
  cancel: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.CANCELLED,
  expire: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.EXPIRED,
  archive: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ARCHIVED,
  hold: EOLE_OPPORTUNITY_LIFECYCLE_STATUS.ON_HOLD,
};

export const EOLE_DEFAULT_MAX_HOLD_PERIOD_DAYS = 30;
