export {
  EPNE_AGREEMENT_LIFECYCLE_ACTION_MAP,
  EPNE_AGREEMENT_LIFECYCLE_STATUS,
  EPNE_AGREEMENT_LIFECYCLE_TRANSITIONS,
  EPNE_FRAMEWORK_VERSION,
  EPNE_MAX_HIERARCHY_DEPTH,
  EPNE_PARTNER_CATEGORIES,
  EPNE_PARTNER_LIFECYCLE_ACTION_MAP,
  EPNE_PARTNER_LIFECYCLE_STATUS,
  EPNE_PARTNER_LIFECYCLE_TRANSITIONS,
  EPNE_PARTNER_TYPES,
} from "./lifecycle";

export {
  EPNE_DEFAULT_RELATIONSHIP_TYPES,
  EPNE_RELATIONSHIP_TYPE_CODES,
} from "./relationship-types";

export type { EpneDefaultRelationshipTypeConfig, EpneRelationshipTypeCode } from "./relationship-types";
