/**
 * Enterprise Initial Data Collection catalog — single SSOT for product/borrower forms.
 *
 * Consumed by Partner Opportunity Journey config (Catalyst Connect projection).
 * Adding / removing / changing a field here must automatically appear in Connect
 * via GET /api/partner/opportunity-journey/config — no Connect release for field lists.
 */

import type { IdcCatalog, IdcSectionDef } from "@/types/enterprise-initial-data-collection";

export const ENTERPRISE_IDC_VERSION = "CO-WP-IDC-001";

/** Progressive Contact — Primary Applicant minimum + optional city. */
export const ENTERPRISE_IDC_CUSTOMER_CAPTURE = {
  title: "Customer",
  description:
    "Search the Enterprise Customer Registry or create a provisional Primary Applicant (Full Name + Mobile).",
  searchMinMobileDigits: 6,
  fields: [
    {
      key: "mobile",
      label: "Mobile number",
      control: "text" as const,
      required: true,
      placeholder: "10-digit mobile",
      helpText: "Primary Applicant mobile — used for Enterprise customer search.",
      inputMode: "tel" as const,
      displayOrder: 10,
      validation: {
        minLength: 10,
        maxLength: 15,
        pattern: "^[0-9+\\-\\s]{10,15}$",
        patternMessage: "Enter a valid mobile number (at least 10 digits).",
      },
    },
    {
      key: "displayName",
      label: "Full name",
      control: "text" as const,
      required: true,
      placeholder: "Customer full name",
      helpText: "Minimum identity for Progressive Contact create.",
      displayOrder: 20,
      validation: { minLength: 2, maxLength: 120 },
    },
    {
      key: "city",
      label: "City",
      control: "city_search" as const,
      required: false,
      placeholder: "Search city…",
      helpText: "Select from Enterprise City Master — type to search.",
      displayOrder: 30,
      validation: { maxLength: 80 },
    },
  ],
};

/** Detail sections — product-wise / borrower-type-wise Initial Data Collection. */
export const ENTERPRISE_IDC_DETAIL_SECTIONS: IdcSectionDef[] = [
  {
    sectionId: "employment_information",
    name: "Employment Information",
    description: "Employment and income profile",
    displayOrder: 20,
    visibility: "visible",
    mandatory: true,
    visibleWhenBorrower: "individual",
    valueBucket: "borrower",
    fields: [
      {
        key: "employmentTypeCode",
        label: "Employment Type",
        control: "select",
        required: true,
        optionSet: "employmentType",
        helpText: "Drives which employment fields appear next.",
        displayOrder: 10,
      },
      {
        key: "employerName",
        label: "Employer",
        control: "text",
        required: false,
        helpText: "Current employer name.",
        displayOrder: 20,
        visibleWhenField: "employmentTypeCode",
        visibleWhenValues: ["salaried"],
      },
      {
        key: "occupation",
        label: "Occupation",
        control: "select",
        required: false,
        optionSet: "occupation",
        placeholder: "Search occupation…",
        helpText: "Profession or business activity.",
        displayOrder: 30,
        visibleWhenField: "employmentTypeCode",
        visibleWhenValues: ["self-employed-professional", "self-employed-business"],
      },
      {
        key: "monthlyIncomeLabel",
        label: "Monthly Income",
        control: "text",
        placeholder: "₹ amount",
        helpText: "Approximate monthly income.",
        required: false,
        displayOrder: 40,
        inputMode: "decimal",
      },
    ],
  },
  {
    sectionId: "business_information",
    name: "Business Information",
    description: "Company / Business as Primary Borrower",
    displayOrder: 15,
    visibility: "visible",
    mandatory: true,
    visibleWhenBorrower: "company",
    valueBucket: "borrower",
    fields: [
      {
        key: "constitution",
        label: "Constitution",
        control: "select",
        required: true,
        optionSet: "constitution",
        helpText: "Legal constitution of the entity.",
        displayOrder: 10,
      },
      {
        key: "companyName",
        label: "Company Name",
        control: "text",
        required: true,
        helpText: "Registered / trading name.",
        displayOrder: 20,
        validation: { minLength: 2, maxLength: 160 },
      },
      {
        key: "businessVintageYears",
        label: "Business Vintage",
        control: "text",
        placeholder: "Years",
        helpText: "Years in business.",
        required: false,
        displayOrder: 30,
        inputMode: "numeric",
      },
      {
        key: "industry",
        label: "Industry",
        control: "select",
        optionSet: "industry",
        required: false,
        helpText: "Primary industry classification.",
        displayOrder: 40,
      },
      {
        key: "gstin",
        label: "GST",
        control: "text",
        required: false,
        helpText: "GSTIN when registered.",
        displayOrder: 50,
        validation: {
          pattern: "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$",
          patternMessage: "Enter a valid 15-character GSTIN.",
          maxLength: 15,
        },
      },
    ],
  },
  {
    sectionId: "financial_information",
    name: "Financial Information",
    description: "Turnover and financial scale",
    displayOrder: 25,
    visibility: "visible",
    mandatory: false,
    visibleWhenBorrower: "company",
    valueBucket: "borrower",
    fields: [
      {
        key: "annualTurnoverLabel",
        label: "Annual Turnover",
        control: "text",
        placeholder: "₹ amount",
        helpText: "Approximate annual turnover.",
        required: false,
        displayOrder: 10,
        inputMode: "decimal",
      },
    ],
  },
  {
    sectionId: "property_information",
    name: "Property Information",
    description: "Property details for secured products",
    displayOrder: 40,
    visibility: "visible",
    mandatory: true,
    visibleWhenBorrower: "any",
    visibleWhenProductFamilies: ["HOME_LOAN", "LAP"],
    valueBucket: "product",
    fields: [
      {
        key: "propertyCity",
        label: "Property City",
        control: "city_search",
        required: true,
        placeholder: "Search city…",
        helpText: "City where the property is located — Enterprise City Master.",
        displayOrder: 10,
        validation: { minLength: 2, maxLength: 80 },
      },
      {
        key: "propertyType",
        label: "Property Type",
        control: "select",
        required: false,
        optionSet: "propertyType",
        helpText: "From Enterprise Product / Property Type master.",
        displayOrder: 20,
        visibleWhenProductFamilies: ["HOME_LOAN"],
      },
      {
        key: "propertyUsage",
        label: "Property Usage",
        control: "select",
        required: false,
        optionSet: "propertyUsage",
        helpText: "From Enterprise Occupancy master.",
        displayOrder: 30,
        visibleWhenProductFamilies: ["LAP"],
      },
    ],
  },
  {
    sectionId: "loan_requirement",
    name: "Loan Requirement",
    description: "Amount, lending type, and transaction type",
    displayOrder: 50,
    visibility: "visible",
    mandatory: true,
    visibleWhenBorrower: "any",
    valueBucket: "requirement",
    fields: [
      {
        key: "requestedAmountLabel",
        label: "Required Amount (₹)",
        control: "text",
        placeholder: "e.g. ₹50 Lakh",
        helpText: "Amount the customer requires.",
        required: true,
        displayOrder: 10,
        inputMode: "decimal",
        validation: { minLength: 1, maxLength: 40 },
      },
      {
        key: "lendingType",
        label: "Lending Type",
        control: "select",
        optionSet: "lendingType",
        required: false,
        helpText: "Secured or Unsecured — leave blank if not yet known.",
        displayOrder: 20,
        defaultValue: "",
      },
      {
        key: "transactionType",
        label: "Transaction Type",
        control: "select",
        optionSet: "transactionType",
        required: false,
        helpText: "Fresh or Balance Transfer.",
        displayOrder: 30,
      },
      {
        key: "currentLendingInstitution",
        label: "Current Lending Institution",
        control: "lender_search",
        required: true,
        placeholder: "Search lender…",
        helpText: "Select from Enterprise Lender Registry — Balance Transfer only.",
        displayOrder: 35,
        visibleWhenField: "transactionType",
        visibleWhenValues: ["balance_transfer"],
        validation: { minLength: 2, maxLength: 120 },
      },
      {
        key: "outstandingLoanAmountLabel",
        label: "Outstanding Loan Amount",
        control: "text",
        placeholder: "₹ amount",
        required: true,
        helpText: "Current outstanding on the loan being transferred.",
        displayOrder: 36,
        inputMode: "decimal",
        visibleWhenField: "transactionType",
        visibleWhenValues: ["balance_transfer"],
        validation: { minLength: 1, maxLength: 40 },
      },
      {
        key: "loanPurpose",
        label: "Loan Purpose",
        control: "text",
        required: false,
        helpText: "Business purpose of the facility.",
        displayOrder: 40,
        visibleWhenProductFamilies: ["BUSINESS_LOAN"],
      },
    ],
  },
  {
    sectionId: "additional_information",
    name: "Additional Information",
    description: "Optional notes for the Opportunity",
    displayOrder: 90,
    visibility: "visible",
    mandatory: false,
    visibleWhenBorrower: "any",
    valueBucket: "requirement",
    fields: [
      {
        key: "remarks",
        label: "Notes / Remarks",
        control: "textarea",
        required: false,
        helpText: "Optional context for the internal team.",
        displayOrder: 10,
        validation: { maxLength: 2000 },
      },
    ],
  },
];

export function getEnterpriseIdcCatalog(): IdcCatalog {
  return {
    version: ENTERPRISE_IDC_VERSION,
    customerCapture: ENTERPRISE_IDC_CUSTOMER_CAPTURE,
    detailSections: ENTERPRISE_IDC_DETAIL_SECTIONS,
  };
}
