import type { EnterpriseAccountingCreditNoteDto } from "@/types/enterprise-accounting-credit-note";
import type { EnterpriseAccountingPaymentDto } from "@/types/enterprise-accounting-payment";

export type RaiseEnterpriseAccountingInvoiceInput = {
  accountingCaseId: string;
  rowVersion: number;
  gstRateId: string;
  invoiceDate?: string;
  dueDate?: string | null;
  tdsAmount?: number | null;
};

export type EnterpriseAccountingInvoiceDto = {
  id: string;
  organizationId: string;
  accountingCaseId: string;
  dealId: string;
  opportunityId: string | null;
  invoicePartyId: string;
  gstRateId: string;
  productId: string | null;
  productCode: string | null;
  productLabel: string | null;
  productFamily: string;
  invoiceProductPrefix: string;
  financialYearKey: string;
  sequenceNumber: number;
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string | null;
  confirmationReference: string;
  partyBillingName: string;
  partyGstin: string | null;
  partyPan: string | null;
  partyBillingAddress: string | null;
  partyStateLabel: string | null;
  partyGstStatus: string | null;
  partyTdsApplicable: boolean;
  partyTdsRatePercent: number | null;
  partyDisplayName: string;
  taxableValue: number;
  gstRatePercent: number;
  gstAmount: number;
  invoiceTotal: number;
  tdsRatePercent: number | null;
  tdsAmount: number;
  netReceivable: number;
  amountReceived: number;
  creditNoteAmount: number;
  outstanding: number;
  paymentStatus: string;
  documentStatus: string;
  raisedBy: string;
  raisedAt: string;
  cancelledAt: string | null;
  cancelledBy: string | null;
  cancellationReason: string | null;
  rowVersion: number;
  createdAt: string;
  updatedAt: string;
  dealNumber?: string | null;
  customerName?: string | null;
  payments: EnterpriseAccountingPaymentDto[];
  creditNotes: EnterpriseAccountingCreditNoteDto[];
};
