/**
 * Enterprise Asset Framework (EAF) — Sprint 1 Foundation.
 *
 * Generic parent model for every business object in Catalyst One.
 * Module-agnostic. No loan, customer, lender, or product references.
 *
 * EAL (Enterprise Asset Library) governs reusable library assets.
 * EAF provides the common enterprise DNA inherited by all domain entities.
 */

// ---------------------------------------------------------------------------
// Identifiers & status primitives (configuration-driven codes)
// ---------------------------------------------------------------------------

/** Internal immutable UUID — primary persistence key. */
export type EafInternalId = string;

/** Public identity — populated later by Identity Engine; optional at creation. */
export type EafPublicIdentity = string;

/** Asset type code — resolved via EAF Asset Type Registry (not hardcoded). */
export type EafAssetTypeCode = string;

/** Lifecycle state code — resolved via EAF Lifecycle Definition (not hardcoded). */
export type EafLifecycleStateCode = string;

/** Relationship type code — resolved via EAF Relationship Type Registry. */
export type EafRelationshipTypeCode = string;

// ---------------------------------------------------------------------------
// Base Enterprise Asset — common parent model
// ---------------------------------------------------------------------------

/**
 * Every enterprise asset inherits this shape.
 * Domain modules extend via `EafExtendedAsset<TMetadata>` — never duplicate base fields.
 */
export interface EafBaseAsset {
  /** Internal UUID (immutable). */
  id: EafInternalId;

  /** Public identity — generated by Identity Engine when assigned. */
  publicIdentity?: EafPublicIdentity;

  /** Asset type code from Asset Type Registry. */
  assetType: EafAssetTypeCode;

  assetName: string;
  description: string;

  /** Lifecycle state code from configured lifecycle definition. */
  lifecycleState: EafLifecycleStateCode;

  /** Category code — taxonomy from configuration. */
  category: string;

  tags: string[];

  /** Owner reference (user/team/org unit id). */
  owner: string;

  createdBy: string;
  createdOn: string;
  modifiedBy: string;
  modifiedOn: string;

  /** Semantic version string (e.g. "1.0.0") — see Version Framework. */
  version: string;

  effectiveFrom?: string;
  effectiveTo?: string;

  activeFlag: boolean;
  archiveFlag: boolean;

  remarks?: string;
}

/** Domain-specific metadata extends base without duplicating core fields. */
export interface EafExtendedAsset<TMetadata extends EafMetadataBag = EafMetadataBag>
  extends EafBaseAsset {
  metadata: TMetadata;
}

export type EafMetadataBag = Record<string, string | number | boolean | string[] | null>;

// ---------------------------------------------------------------------------
// Asset Type Registry (configuration)
// ---------------------------------------------------------------------------

export interface EafAssetTypeDefinition {
  id: string;
  assetTypeCode: EafAssetTypeCode;
  label: string;
  description: string;
  /** Lifecycle definition to apply for this asset type. */
  lifecycleDefinitionId: string;
  /** Optional default category code. */
  defaultCategory?: string;
  enabled: boolean;
  sortOrder: number;
}

// ---------------------------------------------------------------------------
// Lifecycle Framework (configuration-driven)
// ---------------------------------------------------------------------------

export interface EafLifecycleStateDefinition {
  stateCode: EafLifecycleStateCode;
  label: string;
  description: string;
  sortOrder: number;
  isTerminal: boolean;
  /** When true, asset may be operationally active while in this state. */
  allowsOperationalActive: boolean;
}

export interface EafLifecycleTransitionDefinition {
  id: string;
  fromStateCode: EafLifecycleStateCode;
  toStateCode: EafLifecycleStateCode;
  label: string;
  requiresApproval: boolean;
  enabled: boolean;
}

export interface EafLifecycleDefinition {
  id: string;
  lifecycleCode: string;
  label: string;
  description: string;
  states: EafLifecycleStateDefinition[];
  transitions: EafLifecycleTransitionDefinition[];
  defaultStateCode: EafLifecycleStateCode;
  enabled: boolean;
}

// ---------------------------------------------------------------------------
// Relationship Framework
// ---------------------------------------------------------------------------

export type EafRelationshipCardinality =
  | "one_to_one"
  | "one_to_many"
  | "many_to_one"
  | "many_to_many";

export interface EafRelationshipTypeDefinition {
  id: string;
  relationshipTypeCode: EafRelationshipTypeCode;
  label: string;
  description: string;
  sourceAssetTypeCodes: EafAssetTypeCode[];
  targetAssetTypeCodes: EafAssetTypeCode[];
  cardinality: EafRelationshipCardinality;
  bidirectional: boolean;
  enabled: boolean;
}

export interface EafAssetRelationship {
  id: string;
  relationshipTypeCode: EafRelationshipTypeCode;
  sourceAssetId: EafInternalId;
  targetAssetId: EafInternalId;
  label?: string;
  effectiveFrom?: string;
  effectiveTo?: string;
  activeFlag: boolean;
  createdBy: string;
  createdOn: string;
  metadata?: EafMetadataBag;
}

// ---------------------------------------------------------------------------
// Version Framework
// ---------------------------------------------------------------------------

export interface EafAssetVersionRecord {
  id: string;
  assetId: EafInternalId;
  version: string;
  majorVersion: number;
  minorVersion: number;
  patchVersion: number;
  changeSummary: string;
  snapshotRef: string;
  createdBy: string;
  createdOn: string;
  isCurrent: boolean;
}

// ---------------------------------------------------------------------------
// Audit Framework
// ---------------------------------------------------------------------------

export type EafAuditAction =
  | "created"
  | "modified"
  | "deleted"
  | "restored"
  | "lifecycle_changed"
  | "version_created"
  | "relationship_added"
  | "relationship_removed"
  | "archived";

export interface EafAuditEntry {
  id: string;
  assetId: EafInternalId;
  action: EafAuditAction;
  actorId: string;
  timestamp: string;
  previousStateRef?: string;
  newStateRef?: string;
  changeSetRef?: string;
  remarks?: string;
}

// ---------------------------------------------------------------------------
// Metadata Hooks (architecture only — no UI)
// ---------------------------------------------------------------------------

export interface EafDynamicFieldDefinition {
  id: string;
  fieldCode: string;
  label: string;
  dataType: "string" | "number" | "boolean" | "date" | "enum" | "json";
  required: boolean;
  validationRuleRefs: string[];
  layoutSectionRef?: string;
  enabled: boolean;
}

export interface EafDynamicLayoutDefinition {
  id: string;
  layoutCode: string;
  label: string;
  sectionRefs: string[];
  applicableAssetTypeCodes: EafAssetTypeCode[];
  enabled: boolean;
}

export interface EafDynamicFormDefinition {
  id: string;
  formCode: string;
  label: string;
  layoutDefinitionId: string;
  fieldDefinitionIds: string[];
  applicableAssetTypeCodes: EafAssetTypeCode[];
  enabled: boolean;
}

export interface EafValidationRuleDefinition {
  id: string;
  ruleCode: string;
  label: string;
  expressionRef: string;
  severity: "error" | "warning" | "info";
  enabled: boolean;
}

export interface EafMetadataHookBundle {
  fieldDefinitions: EafDynamicFieldDefinition[];
  layoutDefinitions: EafDynamicLayoutDefinition[];
  formDefinitions: EafDynamicFormDefinition[];
  validationRules: EafValidationRuleDefinition[];
}

// ---------------------------------------------------------------------------
// Permissions Hook (architecture only)
// ---------------------------------------------------------------------------

export interface EafRolePermissionHook {
  id: string;
  roleRef: string;
  assetTypeCode: EafAssetTypeCode;
  permissionCodes: string[];
  enabled: boolean;
}

export interface EafVisibilityRuleHook {
  id: string;
  ruleCode: string;
  label: string;
  expressionRef: string;
  applicableAssetTypeCodes: EafAssetTypeCode[];
  enabled: boolean;
}

export interface EafWorkspaceProfileHook {
  id: string;
  profileCode: string;
  label: string;
  visibilityRuleIds: string[];
  layoutDefinitionIds: string[];
  enabled: boolean;
}

export interface EafPermissionHookBundle {
  rolePermissions: EafRolePermissionHook[];
  visibilityRules: EafVisibilityRuleHook[];
  workspaceProfiles: EafWorkspaceProfileHook[];
}

// ---------------------------------------------------------------------------
// Search Hook (architecture only)
// ---------------------------------------------------------------------------

export interface EafSearchMetadata {
  assetId: EafInternalId;
  assetType: EafAssetTypeCode;
  searchableText: string;
  facetCodes: string[];
  indexPriority: number;
  lastIndexedOn?: string;
}

export interface EafSearchIndexFieldDefinition {
  id: string;
  fieldCode: string;
  label: string;
  assetTypeCodes: EafAssetTypeCode[];
  boost: number;
  enabled: boolean;
}

// ---------------------------------------------------------------------------
// AI Hook (architecture only)
// ---------------------------------------------------------------------------

export interface EafAiMetadata {
  assetId: EafInternalId;
  aiSummary?: string;
  aiTags: string[];
  aiIndexRef?: string;
  lastAiProcessedOn?: string;
}

export interface EafAiHookDefinition {
  id: string;
  hookCode: string;
  label: string;
  applicableAssetTypeCodes: EafAssetTypeCode[];
  capabilities: Array<"summary" | "tags" | "index">;
  enabled: boolean;
}

// ---------------------------------------------------------------------------
// Registry entries
// ---------------------------------------------------------------------------

export interface EafAssetRegistryEntry {
  asset: EafBaseAsset;
  searchMetadata?: EafSearchMetadata;
  aiMetadata?: EafAiMetadata;
}

export interface EafFrameworkRegistrySnapshot {
  assetTypes: EafAssetTypeDefinition[];
  lifecycleDefinitions: EafLifecycleDefinition[];
  relationshipTypes: EafRelationshipTypeDefinition[];
  metadataHooks: EafMetadataHookBundle;
  permissionHooks: EafPermissionHookBundle;
  searchIndexFields: EafSearchIndexFieldDefinition[];
  aiHooks: EafAiHookDefinition[];
}
