/**
 * CO-WP-LOD-001 — Configurable Partner LOD presentation (Catalyst One).
 */

import type { PartnerLodPresentationDto } from "@/types/enterprise-partner-lod";

export const PARTNER_LOD_ENGINE_VERSION = "CO-WP-LOD-001";

export const PARTNER_LOD_PRESENTATION: PartnerLodPresentationDto = {
  stepTitle: "Required Documents",
  stepDescription:
    "Document checklist generated by Catalyst One from product, borrower profile, and enterprise configuration. Upload only what is listed.",
  emptyHeadline: "Checklist not ready",
  emptyMessage:
    "Catalyst One could not generate a document list for this Opportunity yet. Complete Initial Data Collection (product and borrower details) and try again.",
  missingLabel: "Missing",
  uploadCtaLabel: "Upload",
  replaceCtaLabel: "Replace",
  previewCtaLabel: "Preview",
};
