/**
 * CO-ARCH-004 — Indian lending institution master seed (minimum baseline + nationally relevant).
 * CO-LR-006 — Merged with comprehensive expansion catalogue (idempotent seedKeys).
 * CO-LR-008 — Gap-fill for Product Owner master population (idempotent seedKeys).
 * Codes are allocated at bootstrap as LND000001…; seedKey is stable for idempotent upsert.
 */
import type {
  LenderInstitutionCategory,
  LenderMasterClassification,
  LenderRegistryProductCode,
} from "@/types/enterprise-lender-registry";
import { getLenderBrandingBySeedKey } from "./branding-catalog";
import { buildCoLr006LenderMasterEntries } from "./master-seed-catalog-co-lr-006";
import { buildCoLr008LenderMasterEntries } from "./master-seed-catalog-co-lr-008";

export const CO_ARCH_004_MASTER_SEED_VERSION = 4;
/** CO-LR-006 — production-ready comprehensive master seed revision. */
export const CO_LR_006_CATALOG_VERSION = 1;
/** CO-LR-008 — master population gap-fill revision. */
export const CO_LR_008_CATALOG_VERSION = 1;

export interface LenderMasterSeedEntry {
  /** Stable idempotent key (not the enterprise LND code). */
  seedKey: string;
  legalName: string;
  displayName: string;
  shortName: string;
  aliases: string[];
  classification: LenderMasterClassification;
  institutionCategory: LenderInstitutionCategory;
  /**
   * Enterprise Lender Category code (SSOT for registry filters).
   * Defaults to institutionCategory when omitted.
   * CO-LM-003 — Foreign Banks use `foreign_bank`.
   */
  categoryCode?: string;
  /** CO-LM-003 — default master seed row (always present in every environment). */
  defaultRecord?: boolean;
  website?: string;
  /**
   * CO-LW-005 — Official marketing brand name (defaults to displayName).
   * Logo / brand asset live on `logoUrl` — never hardcode in UI.
   */
  brandName?: string;
  /** CO-LW-005 — Official logo / brand asset URL (verified only). */
  logoUrl?: string;
  headquartersLabel?: string;
  customerCarePhone?: string;
  customerCareEmail?: string;
  rbiRegulated?: boolean;
  panIndia?: boolean;
  productsSupported: LenderRegistryProductCode[];
}

const BANK_HL = [
  "home_loan",
  "home_loan_bt",
  "lap",
  "personal_loan",
  "business_loan",
  "working_capital",
] as const satisfies LenderRegistryProductCode[];

const HFC_HL = [
  "home_loan",
  "home_loan_bt",
  "lap",
  "construction_funding",
] as const satisfies LenderRegistryProductCode[];

const NBFC_MIX = [
  "personal_loan",
  "business_loan",
  "working_capital",
  "lap",
  "home_loan",
] as const satisfies LenderRegistryProductCode[];

const GOLD_NBFC = ["gold_loan", "personal_loan", "business_loan"] as const satisfies LenderRegistryProductCode[];

function entry(
  partial: Omit<LenderMasterSeedEntry, "rbiRegulated" | "panIndia" | "productsSupported"> & {
    productsSupported?: LenderRegistryProductCode[];
    rbiRegulated?: boolean;
    panIndia?: boolean;
  },
): LenderMasterSeedEntry {
  return {
    rbiRegulated: true,
    panIndia: true,
    productsSupported: [...BANK_HL],
    ...partial,
  };
}

/** Public Sector Banks */
const PUBLIC_SECTOR: LenderMasterSeedEntry[] = [
  entry({
    seedKey: "sbi",
    legalName: "State Bank of India",
    displayName: "State Bank of India",
    shortName: "SBI",
    aliases: ["SBI", "State Bank", "State Bank of India Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.sbi.co.in",
    headquartersLabel: "Mumbai",
    customerCarePhone: "1800 1234",
    customerCareEmail: "contactcentre@sbi.co.in",
  }),
  entry({
    seedKey: "bob",
    legalName: "Bank of Baroda",
    displayName: "Bank of Baroda",
    shortName: "BoB",
    aliases: ["BOB", "Bank of Baroda Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.bankofbaroda.in",
    headquartersLabel: "Vadodara",
  }),
  entry({
    seedKey: "pnb",
    legalName: "Punjab National Bank",
    displayName: "Punjab National Bank",
    shortName: "PNB",
    aliases: ["PNB", "Punjab National Bank Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.pnbindia.in",
    headquartersLabel: "New Delhi",
  }),
  entry({
    seedKey: "canara",
    legalName: "Canara Bank",
    displayName: "Canara Bank",
    shortName: "Canara",
    aliases: ["Canara Bank Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.canarabank.com",
    headquartersLabel: "Bengaluru",
  }),
  entry({
    seedKey: "union",
    legalName: "Union Bank of India",
    displayName: "Union Bank of India",
    shortName: "Union",
    aliases: ["Union Bank", "Union Bank of India Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.unionbankofindia.co.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "indian_bank",
    legalName: "Indian Bank",
    displayName: "Indian Bank",
    shortName: "Indian Bank",
    aliases: ["Indian Bank Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.indianbank.in",
    headquartersLabel: "Chennai",
  }),
  entry({
    seedKey: "boi",
    legalName: "Bank of India",
    displayName: "Bank of India",
    shortName: "BoI",
    aliases: ["BOI", "Bank of India Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.bankofindia.co.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "cbi",
    legalName: "Central Bank of India",
    displayName: "Central Bank of India",
    shortName: "CBI",
    aliases: ["Central Bank", "Central Bank of India Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.centralbankofindia.co.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "iob",
    legalName: "Indian Overseas Bank",
    displayName: "Indian Overseas Bank",
    shortName: "IOB",
    aliases: ["IOB", "Indian Overseas Bank Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.iob.in",
    headquartersLabel: "Chennai",
  }),
  entry({
    seedKey: "uco",
    legalName: "UCO Bank",
    displayName: "UCO Bank",
    shortName: "UCO",
    aliases: ["United Commercial Bank", "UCO Bank Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.ucobank.com",
    headquartersLabel: "Kolkata",
  }),
  entry({
    seedKey: "bom",
    legalName: "Bank of Maharashtra",
    displayName: "Bank of Maharashtra",
    shortName: "BoM",
    aliases: ["BOM", "Bank of Maharashtra Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://www.bankofmaharashtra.in",
    headquartersLabel: "Pune",
  }),
  entry({
    seedKey: "psb",
    legalName: "Punjab & Sind Bank",
    displayName: "Punjab & Sind Bank",
    shortName: "PSB",
    aliases: ["Punjab and Sind Bank", "Punjab & Sind Bank Ltd"],
    classification: "public_sector_bank",
    institutionCategory: "bank",
    website: "https://punjabandsindbank.co.in",
    headquartersLabel: "New Delhi",
  }),
];

/** Private Sector Banks */
const PRIVATE_SECTOR: LenderMasterSeedEntry[] = [
  entry({
    seedKey: "hdfc",
    legalName: "HDFC Bank Limited",
    displayName: "HDFC Bank",
    shortName: "HDFC",
    aliases: ["HDFC", "HDFC Bank", "HDFC Bank Ltd", "Housing Development Finance Corporation Bank"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.hdfcbank.com",
    headquartersLabel: "Mumbai",
    customerCarePhone: "1800 202 6161",
    customerCareEmail: "support@hdfcbank.com",
  }),
  entry({
    seedKey: "icici",
    legalName: "ICICI Bank Limited",
    displayName: "ICICI Bank",
    shortName: "ICICI",
    aliases: ["ICICI", "ICICI Bank", "ICICI Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.icicibank.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "axis",
    legalName: "Axis Bank Limited",
    displayName: "Axis Bank",
    shortName: "Axis",
    aliases: ["Axis", "Axis Bank", "Axis Bank Ltd", "UTI Bank"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.axisbank.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "kotak",
    legalName: "Kotak Mahindra Bank Limited",
    displayName: "Kotak Mahindra Bank",
    shortName: "Kotak",
    aliases: ["Kotak", "Kotak Mahindra", "Kotak Bank", "Kotak Mahindra Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.kotak.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "indusind",
    legalName: "IndusInd Bank Limited",
    displayName: "IndusInd Bank",
    shortName: "IndusInd",
    aliases: ["IndusInd", "IndusInd Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.indusind.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "idfc_first",
    legalName: "IDFC FIRST Bank Limited",
    displayName: "IDFC FIRST Bank",
    shortName: "IDFC FIRST",
    aliases: ["IDFC", "IDFC First", "IDFC First Bank", "IDFC FIRST Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.idfcfirstbank.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "federal",
    legalName: "The Federal Bank Limited",
    displayName: "Federal Bank",
    shortName: "Federal",
    aliases: ["Federal Bank Ltd", "Federal Bank"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.federalbank.co.in",
    headquartersLabel: "Aluva",
  }),
  entry({
    seedKey: "yes",
    legalName: "Yes Bank Limited",
    displayName: "Yes Bank",
    shortName: "Yes",
    aliases: ["YES Bank", "Yes Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.yesbank.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "rbl",
    legalName: "RBL Bank Limited",
    displayName: "RBL Bank",
    shortName: "RBL",
    aliases: ["Ratnakar Bank", "RBL Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.rblbank.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "sib",
    legalName: "South Indian Bank Limited",
    displayName: "South Indian Bank",
    shortName: "SIB",
    aliases: ["SIB", "South Indian Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.southindianbank.com",
    headquartersLabel: "Thrissur",
  }),
  entry({
    seedKey: "karnataka",
    legalName: "Karnataka Bank Limited",
    displayName: "Karnataka Bank",
    shortName: "KBL",
    aliases: ["KBL", "Karnataka Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://karnatakabank.com",
    headquartersLabel: "Mangaluru",
  }),
  entry({
    seedKey: "kvb",
    legalName: "Karur Vysya Bank Limited",
    displayName: "Karur Vysya Bank",
    shortName: "KVB",
    aliases: ["KVB", "Karur Vysya Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.kvb.co.in",
    headquartersLabel: "Karur",
  }),
  entry({
    seedKey: "cub",
    legalName: "City Union Bank Limited",
    displayName: "City Union Bank",
    shortName: "CUB",
    aliases: ["CUB", "City Union Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.cityunionbank.com",
    headquartersLabel: "Kumbakonam",
  }),
  entry({
    seedKey: "dcb",
    legalName: "DCB Bank Limited",
    displayName: "DCB Bank",
    shortName: "DCB",
    aliases: ["Development Credit Bank", "DCB Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.dcbbank.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "tmb",
    legalName: "Tamilnad Mercantile Bank Limited",
    displayName: "Tamilnad Mercantile Bank",
    shortName: "TMB",
    aliases: ["TMB", "Tamilnad Mercantile Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.tmb.in",
    headquartersLabel: "Thoothukudi",
  }),
  entry({
    seedKey: "csb",
    legalName: "CSB Bank Limited",
    displayName: "CSB Bank",
    shortName: "CSB",
    aliases: ["Catholic Syrian Bank", "CSB Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.csb.co.in",
    headquartersLabel: "Thrissur",
  }),
  entry({
    seedKey: "bandhan",
    legalName: "Bandhan Bank Limited",
    displayName: "Bandhan Bank",
    shortName: "Bandhan",
    aliases: ["Bandhan Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://bandhanbank.com",
    headquartersLabel: "Kolkata",
  }),
  entry({
    seedKey: "idbi",
    legalName: "IDBI Bank Limited",
    displayName: "IDBI Bank",
    shortName: "IDBI",
    aliases: ["IDBI", "IDBI Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.idbibank.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "jkb",
    legalName: "Jammu and Kashmir Bank Limited",
    displayName: "Jammu & Kashmir Bank",
    shortName: "J&K Bank",
    aliases: ["J&K Bank", "Jammu & Kashmir Bank", "JK Bank"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.jkbank.com",
    headquartersLabel: "Srinagar",
  }),
  entry({
    seedKey: "nainital",
    legalName: "Nainital Bank Limited",
    displayName: "Nainital Bank",
    shortName: "Nainital",
    aliases: ["Nainital Bank Ltd"],
    classification: "private_sector_bank",
    institutionCategory: "bank",
    website: "https://www.nainitalbank.co.in",
    headquartersLabel: "Nainital",
  }),
];

/** Small Finance Banks */
const SMALL_FINANCE: LenderMasterSeedEntry[] = [
  entry({
    seedKey: "au_sfb",
    legalName: "AU Small Finance Bank Limited",
    displayName: "AU Small Finance Bank",
    shortName: "AU SFB",
    aliases: ["AU Bank", "AU SFB", "AU Small Finance Bank Ltd"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.aubank.in",
    headquartersLabel: "Jaipur",
  }),
  entry({
    seedKey: "equitas_sfb",
    legalName: "Equitas Small Finance Bank Limited",
    displayName: "Equitas Small Finance Bank",
    shortName: "Equitas",
    aliases: ["Equitas", "Equitas SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.equitasbank.com",
    headquartersLabel: "Chennai",
  }),
  entry({
    seedKey: "ujjivan_sfb",
    legalName: "Ujjivan Small Finance Bank Limited",
    displayName: "Ujjivan Small Finance Bank",
    shortName: "Ujjivan",
    aliases: ["Ujjivan", "Ujjivan SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.ujjivansfb.in",
    headquartersLabel: "Bengaluru",
  }),
  entry({
    seedKey: "jana_sfb",
    legalName: "Jana Small Finance Bank Limited",
    displayName: "Jana Small Finance Bank",
    shortName: "Jana",
    aliases: ["Jana SFB", "Janalakshmi"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.janabank.com",
    headquartersLabel: "Bengaluru",
  }),
  entry({
    seedKey: "esaf_sfb",
    legalName: "ESAF Small Finance Bank Limited",
    displayName: "ESAF Small Finance Bank",
    shortName: "ESAF",
    aliases: ["ESAF", "ESAF SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.esafbank.com",
    headquartersLabel: "Thrissur",
  }),
  entry({
    seedKey: "suryoday_sfb",
    legalName: "Suryoday Small Finance Bank Limited",
    displayName: "Suryoday Small Finance Bank",
    shortName: "Suryoday",
    aliases: ["Suryoday", "Suryoday SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.suryodaybank.com",
    headquartersLabel: "Navi Mumbai",
  }),
  entry({
    seedKey: "utkarsh_sfb",
    legalName: "Utkarsh Small Finance Bank Limited",
    displayName: "Utkarsh Small Finance Bank",
    shortName: "Utkarsh",
    aliases: ["Utkarsh", "Utkarsh SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.utkarsh.bank",
    headquartersLabel: "Varanasi",
  }),
  entry({
    seedKey: "capital_sfb",
    legalName: "Capital Small Finance Bank Limited",
    displayName: "Capital Small Finance Bank",
    shortName: "Capital SFB",
    aliases: ["Capital SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.capitalbank.co.in",
    headquartersLabel: "Jalandhar",
  }),
  entry({
    seedKey: "nesfb",
    legalName: "North East Small Finance Bank Limited",
    displayName: "North East Small Finance Bank",
    shortName: "NESFB",
    aliases: ["NESFB", "North East SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://www.nesfb.com",
    headquartersLabel: "Guwahati",
  }),
  entry({
    seedKey: "shivalik_sfb",
    legalName: "Shivalik Small Finance Bank Limited",
    displayName: "Shivalik Small Finance Bank",
    shortName: "Shivalik",
    aliases: ["Shivalik SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://shivalikbank.com",
    headquartersLabel: "Saharanpur",
  }),
  entry({
    seedKey: "unity_sfb",
    legalName: "Unity Small Finance Bank Limited",
    displayName: "Unity Small Finance Bank",
    shortName: "Unity",
    aliases: ["Unity SFB"],
    classification: "small_finance_bank",
    institutionCategory: "bank",
    website: "https://theunitybank.com",
    headquartersLabel: "New Delhi",
  }),
];

/** Housing Finance Companies */
const HFC: LenderMasterSeedEntry[] = [
  entry({
    seedKey: "lic_hfl",
    legalName: "LIC Housing Finance Limited",
    displayName: "LIC Housing Finance",
    shortName: "LIC HFL",
    aliases: ["LIC Housing", "LIC HFL", "LIC Housing Finance Ltd"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.lichousing.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "pnb_housing",
    legalName: "PNB Housing Finance Limited",
    displayName: "PNB Housing Finance",
    shortName: "PNB Housing",
    aliases: ["PNB Housing", "PNB HFL"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.pnbhousing.com",
    headquartersLabel: "New Delhi",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "bajaj_housing",
    legalName: "Bajaj Housing Finance Limited",
    displayName: "Bajaj Housing Finance",
    shortName: "Bajaj HFL",
    aliases: ["Bajaj Housing", "Bajaj HFL"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.bajajhousingfinance.in",
    headquartersLabel: "Pune",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "home_first",
    legalName: "Home First Finance Company India Limited",
    displayName: "Home First Finance",
    shortName: "Home First",
    aliases: ["Home First", "HomeFirst"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://homefirstindia.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "aavas",
    legalName: "Aavas Financiers Limited",
    displayName: "Aavas Financiers",
    shortName: "Aavas",
    aliases: ["Aavas", "AAVAS"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.aavas.in",
    headquartersLabel: "Jaipur",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "india_shelter",
    legalName: "India Shelter Finance Corporation Limited",
    displayName: "India Shelter Finance",
    shortName: "India Shelter",
    aliases: ["India Shelter"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.indiashelter.in",
    headquartersLabel: "Gurugram",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "repco",
    legalName: "Repco Home Finance Limited",
    displayName: "Repco Home Finance",
    shortName: "Repco",
    aliases: ["Repco", "Repco Home"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.repcohome.com",
    headquartersLabel: "Chennai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "gic_housing",
    legalName: "GIC Housing Finance Limited",
    displayName: "GIC Housing Finance",
    shortName: "GICHFL",
    aliases: ["GIC Housing", "GICHFL"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.gichfindia.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "iifl_home",
    legalName: "IIFL Home Finance Limited",
    displayName: "IIFL Home Finance",
    shortName: "IIFL Home",
    aliases: ["IIFL HFL", "IIFL Home"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.iiflhomeloans.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "tata_capital_hfl",
    legalName: "Tata Capital Housing Finance Limited",
    displayName: "Tata Capital Housing Finance",
    shortName: "Tata Capital HFL",
    aliases: ["Tata Capital Housing", "TCHFL"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.tatacapital.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "aditya_birla_housing",
    legalName: "Aditya Birla Housing Finance Limited",
    displayName: "Aditya Birla Housing Finance",
    shortName: "ABHFL",
    aliases: ["Aditya Birla Housing", "ABHFL"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://homefinance.adityabirlacapital.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "godrej_housing",
    legalName: "Godrej Housing Finance Limited",
    displayName: "Godrej Housing Finance",
    shortName: "Godrej HFL",
    aliases: ["Godrej Housing", "Godrej HFL"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.godrejhousingfinance.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "piramal_housing",
    legalName: "Piramal Capital & Housing Finance Limited",
    displayName: "Piramal Housing Finance",
    shortName: "Piramal HFL",
    aliases: ["Piramal Housing", "PCHFL"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.piramalfinance.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "aptus",
    legalName: "Aptus Value Housing Finance India Limited",
    displayName: "Aptus Value Housing Finance",
    shortName: "Aptus",
    aliases: ["Aptus", "Aptus Value Housing"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.aptusindia.com",
    headquartersLabel: "Chennai",
    productsSupported: [...HFC_HL],
  }),
  // Nationally relevant additions
  entry({
    seedKey: "can_fin",
    legalName: "Can Fin Homes Limited",
    displayName: "Can Fin Homes",
    shortName: "Can Fin",
    aliases: ["CanFin", "Can Fin Homes Ltd"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.canfinhomes.com",
    headquartersLabel: "Bengaluru",
    productsSupported: [...HFC_HL],
  }),
  entry({
    seedKey: "sundaram_home",
    legalName: "Sundaram Home Finance Limited",
    displayName: "Sundaram Home Finance",
    shortName: "Sundaram Home",
    aliases: ["Sundaram Home", "Sundaram HFL"],
    classification: "housing_finance_company",
    institutionCategory: "hfc",
    website: "https://www.sundaramhome.in",
    headquartersLabel: "Chennai",
    productsSupported: [...HFC_HL],
  }),
];

/** Major NBFCs */
const NBFC: LenderMasterSeedEntry[] = [
  entry({
    seedKey: "bajaj_finance",
    legalName: "Bajaj Finance Limited",
    displayName: "Bajaj Finance",
    shortName: "Bajaj Finance",
    aliases: ["Bajaj Finserv", "Bajaj Finance Ltd", "BFL"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.bajajfinserv.in",
    headquartersLabel: "Pune",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "tata_capital",
    legalName: "Tata Capital Limited",
    displayName: "Tata Capital",
    shortName: "Tata Capital",
    aliases: ["Tata Capital Ltd", "TCL"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.tatacapital.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "aditya_birla_finance",
    legalName: "Aditya Birla Finance Limited",
    displayName: "Aditya Birla Finance",
    shortName: "ABFL",
    aliases: ["Aditya Birla Finance Ltd", "ABFL"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.adityabirlacapital.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "lt_finance",
    legalName: "L&T Finance Limited",
    displayName: "L&T Finance",
    shortName: "L&T Finance",
    aliases: ["LT Finance", "Larsen & Toubro Finance", "LTF"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.ltfs.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "chola",
    legalName: "Cholamandalam Investment and Finance Company Limited",
    displayName: "Cholamandalam Investment & Finance",
    shortName: "Chola",
    aliases: ["Chola", "Cholamandalam", "CIFCL"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.cholamandalam.com",
    headquartersLabel: "Chennai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "mahindra_finance",
    legalName: "Mahindra & Mahindra Financial Services Limited",
    displayName: "Mahindra Finance",
    shortName: "Mahindra Finance",
    aliases: ["Mahindra Finance", "MMFSL"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.mahindrafinance.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "shriram_finance",
    legalName: "Shriram Finance Limited",
    displayName: "Shriram Finance",
    shortName: "Shriram",
    aliases: ["Shriram Finance Ltd", "Shriram Transport"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.shriramfinance.in",
    headquartersLabel: "Chennai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "poonawalla",
    legalName: "Poonawalla Fincorp Limited",
    displayName: "Poonawalla Fincorp",
    shortName: "Poonawalla",
    aliases: ["Poonawalla", "Magma Fincorp"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://poonawallafincorp.com",
    headquartersLabel: "Pune",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "iifl_finance",
    legalName: "IIFL Finance Limited",
    displayName: "IIFL Finance",
    shortName: "IIFL",
    aliases: ["IIFL", "IIFL Finance Ltd"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.iifl.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "piramal_finance",
    legalName: "Piramal Enterprises Limited",
    displayName: "Piramal Finance",
    shortName: "Piramal Finance",
    aliases: ["Piramal Finance", "Piramal Capital"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.piramalfinance.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "capri_global",
    legalName: "Capri Global Capital Limited",
    displayName: "Capri Global",
    shortName: "Capri",
    aliases: ["Capri Global", "CGCL"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.capriglobal.in",
    headquartersLabel: "Mumbai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "edelweiss",
    legalName: "Edelweiss Financial Services Limited",
    displayName: "Edelweiss Finance",
    shortName: "Edelweiss",
    aliases: ["Edelweiss", "Edelweiss Finance"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.edelweissfin.com",
    headquartersLabel: "Mumbai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "muthoot",
    legalName: "Muthoot Finance Limited",
    displayName: "Muthoot Finance",
    shortName: "Muthoot",
    aliases: ["Muthoot", "Muthoot Finance Ltd"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.muthootfinance.com",
    headquartersLabel: "Kochi",
    productsSupported: [...GOLD_NBFC],
  }),
  entry({
    seedKey: "manappuram",
    legalName: "Manappuram Finance Limited",
    displayName: "Manappuram Finance",
    shortName: "Manappuram",
    aliases: ["Manappuram", "Manappuram Finance Ltd"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.manappuram.com",
    headquartersLabel: "Thrissur",
    productsSupported: [...GOLD_NBFC],
  }),
  entry({
    seedKey: "hinduja_leyland",
    legalName: "Hinduja Leyland Finance Limited",
    displayName: "Hinduja Leyland Finance",
    shortName: "HLF",
    aliases: ["Hinduja Leyland Finance", "HLF"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.hindujaleylandfinance.com",
    headquartersLabel: "Chennai",
    productsSupported: [...NBFC_MIX],
  }),
  entry({
    seedKey: "hero_fincorp",
    legalName: "Hero FinCorp Limited",
    displayName: "Hero FinCorp",
    shortName: "Hero FinCorp",
    aliases: ["Hero Fincorp", "Hero Finance"],
    classification: "nbfc",
    institutionCategory: "nbfc",
    website: "https://www.herofincorp.com",
    headquartersLabel: "New Delhi",
    productsSupported: [...NBFC_MIX],
  }),
];

/** Major Urban Cooperative Banks */
const COOPERATIVE: LenderMasterSeedEntry[] = [
  entry({
    seedKey: "saraswat",
    legalName: "The Saraswat Co-operative Bank Limited",
    displayName: "Saraswat Cooperative Bank",
    shortName: "Saraswat",
    aliases: ["Saraswat Bank", "Saraswat Co-operative Bank"],
    classification: "cooperative_bank",
    institutionCategory: "cooperative",
    website: "https://www.saraswatbank.com",
    headquartersLabel: "Mumbai",
    panIndia: false,
  }),
  entry({
    seedKey: "cosmos",
    legalName: "The Cosmos Co-operative Bank Limited",
    displayName: "Cosmos Cooperative Bank",
    shortName: "Cosmos",
    aliases: ["Cosmos Bank", "Cosmos Co-operative Bank"],
    classification: "cooperative_bank",
    institutionCategory: "cooperative",
    website: "https://www.cosmosbank.com",
    headquartersLabel: "Pune",
    panIndia: false,
  }),
  entry({
    seedKey: "svc",
    legalName: "SVC Co-operative Bank Limited",
    displayName: "Shamrao Vithal Cooperative Bank",
    shortName: "SVC",
    aliases: ["SVC Bank", "Shamrao Vithal", "SVCB"],
    classification: "cooperative_bank",
    institutionCategory: "cooperative",
    website: "https://www.svcbank.com",
    headquartersLabel: "Mumbai",
    panIndia: false,
  }),
  entry({
    seedKey: "nkgsb",
    legalName: "NKGSB Co-operative Bank Limited",
    displayName: "NKGSB Cooperative Bank",
    shortName: "NKGSB",
    aliases: ["NKGSB Bank"],
    classification: "cooperative_bank",
    institutionCategory: "cooperative",
    website: "https://www.nkgsb.bank.in",
    headquartersLabel: "Mumbai",
    panIndia: false,
  }),
  entry({
    seedKey: "abhyudaya",
    legalName: "Abhyudaya Co-operative Bank Limited",
    displayName: "Abhyudaya Cooperative Bank",
    shortName: "Abhyudaya",
    aliases: ["Abhyudaya Bank"],
    classification: "cooperative_bank",
    institutionCategory: "cooperative",
    website: "https://www.abhyudayabank.co.in",
    headquartersLabel: "Mumbai",
    panIndia: false,
  }),
  entry({
    seedKey: "bharat_coop",
    legalName: "Bharat Co-operative Bank (Mumbai) Limited",
    displayName: "Bharat Cooperative Bank",
    shortName: "Bharat Coop",
    aliases: ["Bharat Cooperative Bank", "Bharat Co-op Bank"],
    classification: "cooperative_bank",
    institutionCategory: "cooperative",
    website: "https://www.bharatbank.com",
    headquartersLabel: "Mumbai",
    panIndia: false,
  }),
];

/** Payments banks (nationally relevant) */
const PAYMENTS: LenderMasterSeedEntry[] = [
  entry({
    seedKey: "paytm_payments",
    legalName: "Paytm Payments Bank Limited",
    displayName: "Paytm Payments Bank",
    shortName: "Paytm PB",
    aliases: ["Paytm Bank", "Paytm Payments Bank"],
    classification: "payments_bank",
    institutionCategory: "fintech",
    website: "https://www.paytmbank.com",
    headquartersLabel: "Noida",
    productsSupported: ["personal_loan"],
    panIndia: true,
  }),
  entry({
    seedKey: "airtel_payments",
    legalName: "Airtel Payments Bank Limited",
    displayName: "Airtel Payments Bank",
    shortName: "Airtel PB",
    aliases: ["Airtel Bank", "Airtel Payments Bank"],
    classification: "payments_bank",
    institutionCategory: "fintech",
    website: "https://www.airtel.in/bank",
    headquartersLabel: "New Delhi",
    productsSupported: ["personal_loan"],
  }),
];

/**
 * CO-LM-003 — Default Foreign Banks (approved list only — do not add more here without Product Architecture).
 * Lender Category = Foreign Bank. institutionCategory remains `bank` (Prisma enum; no migration).
 */
const FOREIGN_BANKS: LenderMasterSeedEntry[] = [
  entry({
    seedKey: "standard_chartered",
    legalName: "Standard Chartered Bank",
    displayName: "Standard Chartered Bank",
    shortName: "StanChart",
    aliases: [
      "Standard Chartered",
      "SCB",
      "Standard Chartered Bank India",
      "Standard Chartered Bank Ltd",
    ],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://www.sc.com/in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "hsbc",
    legalName: "The Hongkong and Shanghai Banking Corporation Limited",
    displayName: "HSBC Bank",
    shortName: "HSBC",
    aliases: ["HSBC", "HSBC Bank India", "HSBC India", "Hongkong and Shanghai Banking Corporation"],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://www.hsbc.co.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "dbs_india",
    legalName: "DBS Bank India Limited",
    displayName: "DBS Bank India",
    shortName: "DBS",
    aliases: ["DBS", "DBS Bank", "DBS India", "Development Bank of Singapore"],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://www.dbs.com/in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "deutsche_bank",
    legalName: "Deutsche Bank AG",
    displayName: "Deutsche Bank",
    shortName: "Deutsche",
    aliases: ["Deutsche Bank AG", "Deutsche Bank India", "DB"],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://www.deutschebank.co.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "bank_of_america",
    legalName: "Bank of America, National Association",
    displayName: "Bank of America",
    shortName: "BofA",
    aliases: ["Bank of America N.A.", "BoA", "BofA", "Bank of America India"],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://www.bankofamerica.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "citibank",
    legalName: "Citibank N.A.",
    displayName: "Citibank",
    shortName: "Citi",
    aliases: ["Citi", "Citibank India", "Citibank N.A.", "Citibank NA"],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://www.online.citibank.co.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "shinhan_bank",
    legalName: "Shinhan Bank",
    displayName: "Shinhan Bank",
    shortName: "Shinhan",
    aliases: ["Shinhan", "Shinhan Bank India", "Shinhan Bank Ltd"],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://www.shinhan.com",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "state_bank_mauritius",
    legalName: "SBM Bank (India) Limited",
    displayName: "State Bank of Mauritius",
    shortName: "SBM",
    aliases: [
      "SBM",
      "SBM Bank",
      "SBM Bank India",
      "State Bank of Mauritius Ltd",
      "SBM Bank (India)",
    ],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://www.sbmbank.co.in",
    headquartersLabel: "Mumbai",
  }),
  entry({
    seedKey: "doha_bank",
    legalName: "Doha Bank Q.P.S.C.",
    displayName: "Doha Bank",
    shortName: "Doha",
    aliases: ["Doha Bank India", "Doha Bank QPSC", "Doha Bank Ltd"],
    classification: "foreign_bank",
    institutionCategory: "bank",
    categoryCode: "foreign_bank",
    defaultRecord: true,
    website: "https://in.dohabank.com",
    headquartersLabel: "Mumbai",
  }),
];

const BASELINE_LENDER_MASTER_SEED_CATALOG: LenderMasterSeedEntry[] = [
  ...PUBLIC_SECTOR,
  ...PRIVATE_SECTOR,
  ...SMALL_FINANCE,
  ...HFC,
  ...NBFC,
  ...COOPERATIVE,
  ...PAYMENTS,
  ...FOREIGN_BANKS,
];

export const LENDER_MASTER_SEED_CATALOG: LenderMasterSeedEntry[] = (() => {
  const afterLr006 = [
    ...BASELINE_LENDER_MASTER_SEED_CATALOG,
    ...buildCoLr006LenderMasterEntries(BASELINE_LENDER_MASTER_SEED_CATALOG),
  ];
  const merged = [...afterLr006, ...buildCoLr008LenderMasterEntries(afterLr006)];
  /** CO-LW-005 — attach verified brand assets (logo only when curated). */
  return merged.map((seed) => {
    const brand = getLenderBrandingBySeedKey(seed.seedKey);
    if (!brand) {
      return {
        ...seed,
        brandName: seed.brandName ?? seed.displayName,
      };
    }
    return {
      ...seed,
      brandName: brand.brandName || seed.displayName,
      website: seed.website || brand.website,
      ...(brand.logoUrl ? { logoUrl: brand.logoUrl } : {}),
    };
  });
})();

export function countLenderMasterSeedByClassification(): Record<
  LenderMasterClassification,
  number
> {
  const counts: Record<LenderMasterClassification, number> = {
    public_sector_bank: 0,
    private_sector_bank: 0,
    small_finance_bank: 0,
    housing_finance_company: 0,
    nbfc: 0,
    cooperative_bank: 0,
    payments_bank: 0,
    foreign_bank: 0,
  };
  for (const row of LENDER_MASTER_SEED_CATALOG) {
    counts[row.classification] += 1;
  }
  return counts;
}

/** CO-LM-003 — approved default Foreign Bank seed keys (exactly nine). */
export const CO_LM_003_FOREIGN_BANK_SEED_KEYS = [
  "standard_chartered",
  "hsbc",
  "dbs_india",
  "deutsche_bank",
  "bank_of_america",
  "citibank",
  "shinhan_bank",
  "state_bank_mauritius",
  "doha_bank",
] as const;

export function listDefaultForeignBankSeeds(): LenderMasterSeedEntry[] {
  return LENDER_MASTER_SEED_CATALOG.filter((l) => l.categoryCode === "foreign_bank");
}
