/**
 * CO-FOUNDATION-010 — RIC mock dataset (DEV / historical only).
 *
 * CO-UX-013 — Production Network Workspace MUST NOT import this module.
 * Live path: `live-registry.ts` (Enterprise Contact Registry + ECM relationships).
 */

import type { RicContact, RicRelationship } from "./ric-types";

export const RIC_MOCK_CONTACTS: RicContact[] = [
  {
    id: "ric-01",
    name: "Ramesh Rao",
    category: "CA",
    businessRole: "Partner",
    company: "Rao & Associates",
    relationshipScore: 92,
    colourFamily: "professional",
    lastMeeting: "12 Jun 2026",
    lastCall: "18 Jun 2026",
    lastFollowUp: "20 Jun 2026",
  },
  {
    id: "ric-02",
    name: "Priya Sharma",
    category: "Customer",
    businessRole: "Promoter",
    company: "Sharma Holdings",
    relationshipScore: 88,
    colourFamily: "organisation",
    lastMeeting: "05 Jun 2026",
    lastCall: "15 Jun 2026",
    lastFollowUp: "16 Jun 2026",
  },
  {
    id: "ric-03",
    name: "Skyline Developers",
    category: "Builder",
    businessRole: "Developer",
    company: "Skyline Group",
    relationshipScore: 81,
    colourFamily: "business",
    lastMeeting: "02 Jun 2026",
    lastCall: "10 Jun 2026",
    lastFollowUp: "11 Jun 2026",
  },
  {
    id: "ric-04",
    name: "Anil Mehta",
    category: "Bank",
    businessRole: "Credit Manager",
    company: "HDFC Bank",
    relationshipScore: 85,
    colourFamily: "financial",
    lastMeeting: "08 Jun 2026",
    lastCall: "19 Jun 2026",
    lastFollowUp: "19 Jun 2026",
  },
  {
    id: "ric-05",
    name: "Sneha Kapoor",
    category: "Bank",
    businessRole: "Relationship Manager",
    company: "ICICI Bank",
    relationshipScore: 79,
    colourFamily: "financial",
    lastMeeting: "01 Jun 2026",
    lastCall: "14 Jun 2026",
    lastFollowUp: "14 Jun 2026",
  },
  {
    id: "ric-06",
    name: "Bajaj Housing",
    category: "NBFC",
    businessRole: "Institution",
    company: "Bajaj Housing Finance",
    relationshipScore: 74,
    colourFamily: "financial",
    lastMeeting: "28 May 2026",
    lastCall: "09 Jun 2026",
    lastFollowUp: "09 Jun 2026",
  },
  {
    id: "ric-07",
    name: "Vikram Joshi",
    category: "Relationship Manager",
    businessRole: "RM · West",
    company: "Rupee Catalyst",
    relationshipScore: 90,
    colourFamily: "organisation",
    lastMeeting: "20 Jun 2026",
    lastCall: "21 Jun 2026",
    lastFollowUp: "21 Jun 2026",
  },
  {
    id: "ric-08",
    name: "Adv. Meera Iyer",
    category: "Lawyer",
    businessRole: "Legal Counsel",
    company: "Iyer Legal",
    relationshipScore: 77,
    colourFamily: "government_legal",
    lastMeeting: "30 May 2026",
    lastCall: "07 Jun 2026",
    lastFollowUp: "08 Jun 2026",
  },
  {
    id: "ric-09",
    name: "Pune Valuers Co",
    category: "Valuer",
    businessRole: "Panel Valuer",
    company: "Pune Valuers Co",
    relationshipScore: 72,
    colourFamily: "professional",
    lastMeeting: "22 May 2026",
    lastCall: "03 Jun 2026",
    lastFollowUp: "04 Jun 2026",
  },
  {
    id: "ric-10",
    name: "Kavita Nair",
    category: "Customer",
    businessRole: "Applicant",
    company: "Nair Retail",
    relationshipScore: 83,
    colourFamily: "organisation",
    lastMeeting: "11 Jun 2026",
    lastCall: "17 Jun 2026",
    lastFollowUp: "17 Jun 2026",
  },
  {
    id: "ric-11",
    name: "Prestige Projects",
    category: "Builder",
    businessRole: "Sales Head",
    company: "Prestige Group",
    relationshipScore: 76,
    colourFamily: "business",
    lastMeeting: "25 May 2026",
    lastCall: "06 Jun 2026",
    lastFollowUp: "06 Jun 2026",
  },
  {
    id: "ric-12",
    name: "Rahul Verma",
    category: "Bank",
    businessRole: "Branch Manager",
    company: "Axis Bank",
    relationshipScore: 80,
    colourFamily: "financial",
    lastMeeting: "09 Jun 2026",
    lastCall: "16 Jun 2026",
    lastFollowUp: "16 Jun 2026",
  },
  {
    id: "ric-13",
    name: "Neha Kulkarni",
    category: "CA",
    businessRole: "Senior Manager",
    company: "Kulkarni & Co",
    relationshipScore: 84,
    colourFamily: "professional",
    lastMeeting: "04 Jun 2026",
    lastCall: "13 Jun 2026",
    lastFollowUp: "13 Jun 2026",
  },
  {
    id: "ric-14",
    name: "Kotak Retail Desk",
    category: "Bank",
    businessRole: "Product Desk",
    company: "Kotak Mahindra Bank",
    relationshipScore: 71,
    colourFamily: "financial",
    lastMeeting: "18 May 2026",
    lastCall: "01 Jun 2026",
    lastFollowUp: "02 Jun 2026",
  },
  {
    id: "ric-15",
    name: "Piramal Capital",
    category: "NBFC",
    businessRole: "Institution",
    company: "Piramal Capital",
    relationshipScore: 69,
    colourFamily: "financial",
    lastMeeting: "15 May 2026",
    lastCall: "29 May 2026",
    lastFollowUp: "30 May 2026",
  },
  {
    id: "ric-16",
    name: "Sonal Deshmukh",
    category: "Relationship Manager",
    businessRole: "RM · Pune",
    company: "Rupee Catalyst",
    relationshipScore: 87,
    colourFamily: "organisation",
    lastMeeting: "19 Jun 2026",
    lastCall: "20 Jun 2026",
    lastFollowUp: "20 Jun 2026",
  },
  {
    id: "ric-17",
    name: "Adv. Ravi Desai",
    category: "Lawyer",
    businessRole: "Advocate",
    company: "Desai Chambers",
    relationshipScore: 73,
    colourFamily: "government_legal",
    lastMeeting: "27 May 2026",
    lastCall: "05 Jun 2026",
    lastFollowUp: "05 Jun 2026",
  },
  {
    id: "ric-18",
    name: "Accurate Valuers",
    category: "Valuer",
    businessRole: "Technical Valuer",
    company: "Accurate Valuers",
    relationshipScore: 70,
    colourFamily: "professional",
    lastMeeting: "20 May 2026",
    lastCall: "31 May 2026",
    lastFollowUp: "01 Jun 2026",
  },
  {
    id: "ric-19",
    name: "Amit Shah",
    category: "Customer",
    businessRole: "Director",
    company: "Shah Infra",
    relationshipScore: 86,
    colourFamily: "organisation",
    lastMeeting: "10 Jun 2026",
    lastCall: "18 Jun 2026",
    lastFollowUp: "18 Jun 2026",
  },
  {
    id: "ric-20",
    name: "Lodha Connect",
    category: "Builder",
    businessRole: "Channel Partner Desk",
    company: "Lodha Group",
    relationshipScore: 75,
    colourFamily: "business",
    lastMeeting: "03 Jun 2026",
    lastCall: "12 Jun 2026",
    lastFollowUp: "12 Jun 2026",
  },
];

/** ~40 first-level relationships (undirected for canvas traversal). */
export const RIC_MOCK_RELATIONSHIPS: RicRelationship[] = [
  { id: "rel-01", fromId: "ric-01", toId: "ric-02", label: "Advises" },
  { id: "rel-02", fromId: "ric-01", toId: "ric-03", label: "Audits" },
  { id: "rel-03", fromId: "ric-01", toId: "ric-04", label: "Banker link" },
  { id: "rel-04", fromId: "ric-01", toId: "ric-06", label: "NBFC link" },
  { id: "rel-05", fromId: "ric-01", toId: "ric-07", label: "RM link" },
  { id: "rel-06", fromId: "ric-01", toId: "ric-08", label: "Legal" },
  { id: "rel-07", fromId: "ric-01", toId: "ric-09", label: "Valuation" },
  { id: "rel-08", fromId: "ric-02", toId: "ric-03", label: "Project" },
  { id: "rel-09", fromId: "ric-02", toId: "ric-04", label: "Banking" },
  { id: "rel-10", fromId: "ric-02", toId: "ric-07", label: "Serviced by" },
  { id: "rel-11", fromId: "ric-02", toId: "ric-13", label: "Tax" },
  { id: "rel-12", fromId: "ric-03", toId: "ric-05", label: "Funding" },
  { id: "rel-13", fromId: "ric-03", toId: "ric-09", label: "Panel" },
  { id: "rel-14", fromId: "ric-03", toId: "ric-11", label: "Peer" },
  { id: "rel-15", fromId: "ric-03", toId: "ric-16", label: "RM link" },
  { id: "rel-16", fromId: "ric-04", toId: "ric-07", label: "RM desk" },
  { id: "rel-17", fromId: "ric-04", toId: "ric-10", label: "Customer" },
  { id: "rel-18", fromId: "ric-04", toId: "ric-12", label: "Peer bank" },
  { id: "rel-19", fromId: "ric-05", toId: "ric-10", label: "Customer" },
  { id: "rel-20", fromId: "ric-05", toId: "ric-16", label: "RM link" },
  { id: "rel-21", fromId: "ric-05", toId: "ric-19", label: "Customer" },
  { id: "rel-22", fromId: "ric-06", toId: "ric-07", label: "RM link" },
  { id: "rel-23", fromId: "ric-06", toId: "ric-15", label: "Peer NBFC" },
  { id: "rel-24", fromId: "ric-06", toId: "ric-19", label: "Customer" },
  { id: "rel-25", fromId: "ric-07", toId: "ric-08", label: "Legal" },
  { id: "rel-26", fromId: "ric-07", toId: "ric-16", label: "Team" },
  { id: "rel-27", fromId: "ric-07", toId: "ric-20", label: "Builder desk" },
  { id: "rel-28", fromId: "ric-08", toId: "ric-17", label: "Peer counsel" },
  { id: "rel-29", fromId: "ric-08", toId: "ric-19", label: "Client" },
  { id: "rel-30", fromId: "ric-09", toId: "ric-18", label: "Peer valuer" },
  { id: "rel-31", fromId: "ric-09", toId: "ric-20", label: "Project" },
  { id: "rel-32", fromId: "ric-10", toId: "ric-13", label: "CA" },
  { id: "rel-33", fromId: "ric-10", toId: "ric-16", label: "RM" },
  { id: "rel-34", fromId: "ric-11", toId: "ric-12", label: "Funding" },
  { id: "rel-35", fromId: "ric-11", toId: "ric-18", label: "Valuation" },
  { id: "rel-36", fromId: "ric-12", toId: "ric-14", label: "Peer bank" },
  { id: "rel-37", fromId: "ric-13", toId: "ric-15", label: "NBFC" },
  { id: "rel-38", fromId: "ric-13", toId: "ric-19", label: "Client" },
  { id: "rel-39", fromId: "ric-14", toId: "ric-16", label: "RM desk" },
  { id: "rel-40", fromId: "ric-17", toId: "ric-20", label: "Project legal" },
];

export function getRicContactById(id: string): RicContact | undefined {
  return RIC_MOCK_CONTACTS.find((c) => c.id === id);
}

/** First-level neighbours only — no second hop. */
export function listRicFirstLevel(contactId: string): {
  centre: RicContact | undefined;
  neighbours: RicContact[];
  edges: RicRelationship[];
} {
  const centre = getRicContactById(contactId);
  if (!centre) return { centre: undefined, neighbours: [], edges: [] };

  const edges = RIC_MOCK_RELATIONSHIPS.filter(
    (r) => r.fromId === contactId || r.toId === contactId,
  );
  const neighbourIds = new Set<string>();
  for (const e of edges) {
    neighbourIds.add(e.fromId === contactId ? e.toId : e.fromId);
  }
  const neighbours = [...neighbourIds]
    .map((id) => getRicContactById(id))
    .filter((c): c is RicContact => Boolean(c));

  return { centre, neighbours, edges };
}
