/**
 * CO-MARKETING-MKT-01 — Enterprise Marketing Engine (EME) constants SSOT.
 * Product name: EME. Code prefix: ENTERPRISE_MARKETING_ / MARKETING_
 * (Avoid bare EME_* — reserved collision with Enterprise Metrics Engine.)
 */

export {
  ENTERPRISE_MARKETING_AUDIENCE_IMPORT_ENABLED,
  ENTERPRISE_MARKETING_EMAIL_MODE,
  ENTERPRISE_MARKETING_EXECUTION_DRY_RUN_ENABLED,
  ENTERPRISE_MARKETING_EXECUTION_ENABLED,
  ENTERPRISE_MARKETING_HANDOFF_ENABLED,
  ENTERPRISE_MARKETING_HANDOFF_MODE,
  ENTERPRISE_MARKETING_MASS_HANDOFF_ENABLED,
  ENTERPRISE_MARKETING_PROVIDER_CONNECT_ENABLED,
  ENTERPRISE_MARKETING_SAFETY,
  ENTERPRISE_MARKETING_SHEETS_MODE,
  ENTERPRISE_MARKETING_SHEETS_READ_ENABLED,
  ENTERPRISE_MARKETING_WHATSAPP_MODE,
  type EnterpriseMarketingEmailDeliveryMode,
  type EnterpriseMarketingSheetsMode,
  type EnterpriseMarketingHandoffMode,
  type EnterpriseMarketingWhatsAppDeliveryMode,
} from "./safety";

export {
  MARKETING_SHEETS_AUTH_REF,
  MARKETING_SHEETS_EMAIL_HEADER_ALIASES,
  MARKETING_SHEETS_EXTERNAL_KEY_HEADER_ALIASES,
  MARKETING_SHEETS_PAGE_MAX_ROWS,
  MARKETING_SHEETS_PHONE_HEADER_ALIASES,
  MARKETING_SHEETS_PREVIEW_MAX_ROWS,
  MARKETING_SHEETS_REQUIRED_IDENTITY_GROUPS,
} from "./data-source";

export {
  MARKETING_AUDIENCE_SCAN_MAX_ROWS,
  MARKETING_AUDIENCE_SCAN_PAGE_SIZE,
  MARKETING_FILTER_OPS,
  MARKETING_SUPPRESSION_REASONS,
  type MarketingFilterOp,
  type MarketingSuppressionReason,
} from "./audience";

export {
  MARKETING_ASSET_CATEGORIES,
  MARKETING_ASSET_IMAGE_MIME_TYPES,
  MARKETING_ASSET_MAX_BYTES,
  MARKETING_CONTENT_BLOCK_LABELS,
  MARKETING_CONTENT_BLOCK_TYPES,
  MARKETING_PERSONALIZATION_FALLBACKS,
  MARKETING_PERSONALIZATION_TOKENS,
  type MarketingAssetCategory,
  type MarketingContentBlockType,
  type MarketingPersonalizationToken,
} from "./content";

export {
  MARKETING_EUM_MODULE_ID,
  MARKETING_FEATURE_PERMISSION,
  MARKETING_PERMISSIONS,
  type MarketingPermission,
} from "./permissions";

export {
  MARKETING_CAMPAIGN_ACTIONS,
  MARKETING_CAMPAIGN_STATUSES,
  MARKETING_CHANNELS,
  type MarketingCampaignAction,
  type MarketingCampaignStatus,
  type MarketingChannel,
} from "./lifecycle";

export {
  MARKETING_ACTION_TARGET_STATUS,
  MARKETING_APPROVAL_GATED_ACTIONS,
  MARKETING_CAMPAIGN_REGISTRY_STATUSES,
  MARKETING_CAMPAIGN_STATUS_LABELS,
  MARKETING_LEGAL_TRANSITIONS,
  MARKETING_OPERATIONAL_ACTIONS,
  assertMarketingTransitionAllowed,
  isMarketingTransitionAllowed,
  marketingCampaignEditPolicy,
} from "./transitions";

export {
  MARKETING_DEFAULT_BATCH_POLICY,
  MARKETING_CONTROLLED_TEST_BATCH_SIZES,
  MARKETING_CRON_MAX_CAMPAIGNS_PER_TICK,
  MARKETING_EXECUTION_LEASE_TTL_MS,
  MARKETING_EXECUTION_STREAM_PAGE_SIZE,
} from "./execution";

export {
  MARKETING_EMAIL_DELIVERY_OUTCOMES,
  MARKETING_EMAIL_PROVIDER_ENV_KEYS,
  MARKETING_EMAIL_PROVIDER_TYPES,
  MARKETING_SENDER_VERIFICATION_STATUSES,
} from "./email-delivery";

export {
  MARKETING_DEFAULT_CHANNEL_ELIGIBILITY,
  MARKETING_WHATSAPP_DELIVERY_OUTCOMES,
  MARKETING_WHATSAPP_PROVIDER_ENV_KEYS,
  MARKETING_WHATSAPP_PROVIDER_TYPES,
  MARKETING_WHATSAPP_TEMPLATE_APPROVAL_STATES,
  MARKETING_WHATSAPP_TEMPLATE_CATEGORIES,
} from "./whatsapp-delivery";

export {
  MARKETING_DEFAULT_QUALIFICATION_POLICY,
  MARKETING_HANDOFF_PROCESS_STATES,
  MARKETING_QUALIFICATION_BUSINESS_STATES,
  MARKETING_QUALIFICATION_STATE_LABELS,
} from "./qualification";

export {
  MARKETING_ROUTING_CRITERION_FIELDS,
  MARKETING_ROUTING_CRITERION_LABELS,
  MARKETING_ROUTING_MODES,
  type MarketingRoutingCriterionField,
} from "./routing";

export {
  MARKETING_DEFAULT_NOTIFICATION_CHANNELS,
  MARKETING_HANDOFF_REQUIRED_ACTION,
  MARKETING_NOTIFICATION_ATTEMPT_STATUSES,
  MARKETING_NOTIFICATION_CHANNELS,
  type MarketingNotificationAttemptStatus,
  type MarketingNotificationChannel,
} from "./notification";

export {
  MARKETING_ANALYTICS_RANGE_LABELS,
  MARKETING_ANALYTICS_RANGE_PRESETS,
  MARKETING_ANALYTICS_DEFAULT_PRESET,
  MARKETING_ANALYTICS_NOTICE,
  MARKETING_ENGAGEMENT_EVENT_TYPES,
  marketingChannelEventCapabilities,
} from "./analytics";

export {
  MARKETING_COMMAND_CENTER_SECTIONS,
  type MarketingNavSection,
} from "./navigation";

export const ENTERPRISE_MARKETING_MODULE_ID = "enterprise-marketing-engine" as const;
export const ENTERPRISE_MARKETING_MODULE_TITLE = "Marketing Command Center" as const;
export const ENTERPRISE_MARKETING_ENGINE_NAME = "Enterprise Marketing Engine" as const;
