/**
 * CO-MARKETING-MKT-01 — Enterprise Marketing Engine (EME) constants SSOT.
 * Product name: EME. Code prefix: ENTERPRISE_MARKETING_ / MARKETING_
 * (Avoid bare EME_* — reserved collision with Enterprise Metrics Engine.)
 */

export {
  ENTERPRISE_MARKETING_AUDIENCE_IMPORT_ENABLED,
  ENTERPRISE_MARKETING_EMAIL_MODE,
  ENTERPRISE_MARKETING_EXECUTION_DRY_RUN_ENABLED,
  ENTERPRISE_MARKETING_EXECUTION_ENABLED,
  ENTERPRISE_MARKETING_HANDOFF_ENABLED,
  ENTERPRISE_MARKETING_HANDOFF_MODE,
  ENTERPRISE_MARKETING_MASS_HANDOFF_ENABLED,
  ENTERPRISE_MARKETING_PROVIDER_CONNECT_ENABLED,
  ENTERPRISE_MARKETING_SAFETY,
  ENTERPRISE_MARKETING_SHEETS_MODE,
  ENTERPRISE_MARKETING_SHEETS_READ_ENABLED,
  ENTERPRISE_MARKETING_WHATSAPP_MODE,
  type EnterpriseMarketingEmailDeliveryMode,
  type EnterpriseMarketingSheetsMode,
  type EnterpriseMarketingHandoffMode,
  type EnterpriseMarketingWhatsAppDeliveryMode,
} from "./safety";

export {
  MARKETING_SHEETS_AUTH_REF,
  MARKETING_SHEETS_EMAIL_HEADER_ALIASES,
  MARKETING_SHEETS_EXTERNAL_KEY_HEADER_ALIASES,
  MARKETING_SHEETS_PAGE_MAX_ROWS,
  MARKETING_SHEETS_PHONE_HEADER_ALIASES,
  MARKETING_SHEETS_PREVIEW_MAX_ROWS,
  MARKETING_SHEETS_REQUIRED_IDENTITY_GROUPS,
} from "./data-source";

export {
  MARKETING_AUDIENCE_APPROVAL_SCAN_UNLIMITED,
  MARKETING_AUDIENCE_SCAN_MAX_ROWS,
  MARKETING_AUDIENCE_SCAN_PAGE_SIZE,
  MARKETING_FILTER_OPS,
  MARKETING_SUPPRESSION_REASONS,
  type MarketingFilterOp,
  type MarketingSuppressionReason,
} from "./audience";

export {
  MARKETING_FIXTURE_VISIBLE_LABEL,
  MARKETING_FIXTURE_WORKBOOK_ID,
  MARKETING_GOOGLE_CONFIGURATION_REQUIRED_LABEL,
  MARKETING_NOT_CONFIGURED_LABEL,
  MARKETING_SHEETS_SOURCE_STATUSES,
  MARKETING_WORKBOOK_CONNECTION_LABELS,
  MARKETING_WORKBOOK_CONNECTION_STATES,
  type MarketingSheetsSourceStatus,
  type MarketingWorkbookConnectionState,
} from "./authorised-workbook";

export {
  MARKETING_ASSET_CATEGORIES,
  MARKETING_ASSET_IMAGE_MIME_TYPES,
  MARKETING_ASSET_MAX_BYTES,
  MARKETING_CONTENT_BLOCK_LABELS,
  MARKETING_CONTENT_BLOCK_TYPES,
  MARKETING_VISUAL_EDITOR_PALETTE,
  MARKETING_UNSUBSCRIBE_BLOCK_TYPE,
  MARKETING_EMAIL_SAFE_COLORS,
  MARKETING_EMAIL_SAFE_FONT_STACK,
  MARKETING_TEMPLATE_CATEGORIES,
  MARKETING_TEMPLATE_STATUSES,
  MARKETING_HTML_SOURCE_MODE_DEFAULT,
  type MarketingTemplateCategory,
  type MarketingTemplateStatus,
  MARKETING_PERSONALIZATION_FALLBACKS,
  MARKETING_PERSONALIZATION_TOKENS,
  type MarketingAssetCategory,
  type MarketingContentBlockType,
  type MarketingPersonalizationToken,
} from "./content";

export {
  MARKETING_PERSONALISATION_LABELS,
  MARKETING_PERSONALISATION_SENSITIVE_FIELDS,
  MARKETING_PREVIEW_DESKTOP_MAX_WIDTH,
  MARKETING_PREVIEW_MOBILE_MAX_WIDTH,
  MARKETING_TEST_SEND_ALLOWED_ADDRESSES,
  MARKETING_TEST_SEND_ALLOWED_DOMAINS,
  MARKETING_TEST_SEND_CONFIRMATION_PHRASE,
  MARKETING_TEST_SEND_DRY_RUN_NOTICE,
  MARKETING_TEST_LANE_TITLE,
  MARKETING_PRODUCTION_LANE_TITLE,
} from "./personalisation";

export {
  MARKETING_EUM_MODULE_ID,
  MARKETING_FEATURE_PERMISSION,
  MARKETING_PERMISSIONS,
  type MarketingPermission,
} from "./permissions";

export {
  MARKETING_CAMPAIGN_BUILDER_STEPS,
  MARKETING_CAMPAIGN_OBJECTIVE_OPTIONS,
  MARKETING_AUDIENCE_CATEGORY_OPTIONS,
  MARKETING_BUILDER_SEND_FORBIDDEN_STEP_NUMBERS,
  MARKETING_BUILDER_TIMEZONES,
  MARKETING_BUILDER_UNSAVED_TITLE,
  MARKETING_BUILDER_UNSAVED_MESSAGE,
  MARKETING_BUILDER_DRAFT_SAVE_CONTRACT,
  marketingCampaignBuilderHref,
  type MarketingCampaignBuilderStepId,
} from "./campaign-builder";

export {
  MARKETING_CAMPAIGN_ACTIONS,
  MARKETING_CAMPAIGN_STATUSES,
  MARKETING_CHANNELS,
  type MarketingCampaignAction,
  type MarketingCampaignStatus,
  type MarketingChannel,
} from "./lifecycle";

export {
  MARKETING_BUILDER_CHANNEL_PICKER_OPTIONS,
  MARKETING_CAMPAIGN_CHANNEL_KINDS,
  MARKETING_CHANNEL_CONTRACTS,
  MARKETING_CHANNEL_NOT_CONFIGURED_LABEL,
  MARKETING_CHANNEL_PRODUCT_SURFACES,
  MARKETING_INACTIVE_CHANNEL_KINDS,
  MARKETING_OPERATIONAL_CHANNEL_KIND,
  MARKETING_SMS_SEGMENT_LIMITS,
  MARKETING_WHATSAPP_OPT_IN_REQUIRED,
  type MarketingCampaignChannelKind,
  type MarketingChannelProductSurface,
} from "./channel-contracts";

export {
  MARKETING_ACTION_TARGET_STATUS,
  MARKETING_APPROVAL_GATED_ACTIONS,
  MARKETING_CAMPAIGN_REGISTRY_STATUSES,
  MARKETING_CAMPAIGN_STATUS_LABELS,
  MARKETING_LEGAL_TRANSITIONS,
  MARKETING_OPERATIONAL_ACTIONS,
  assertMarketingTransitionAllowed,
  isMarketingTransitionAllowed,
  marketingCampaignEditPolicy,
} from "./transitions";

export {
  MARKETING_DEFAULT_BATCH_POLICY,
  MARKETING_DEFAULT_BATCH_SIZE,
  MARKETING_DEFAULT_BATCH_INTERVAL_MS,
  MARKETING_CONTROLLED_TEST_BATCH_SIZES,
  MARKETING_CRON_MAX_CAMPAIGNS_PER_TICK,
  MARKETING_EXECUTION_LEASE_TTL_MS,
  MARKETING_EXECUTION_STREAM_PAGE_SIZE,
} from "./execution";

export {
  MARKETING_LIVE_PROVIDER_SENDING_DISABLED,
  MARKETING_STOP_CONFIRMATION_PHRASE,
  MARKETING_BATCH_CONFIRMATION_PHRASE,
  MARKETING_RETRY_CONFIRMATION_PHRASE,
  MARKETING_DELIVERY_OPERATION_LABELS,
} from "./delivery-operations";

export {
  MARKETING_EMAIL_DELIVERY_OUTCOMES,
  MARKETING_EMAIL_PROVIDER_ENV_KEYS,
  MARKETING_EMAIL_PROVIDER_TYPES,
  MARKETING_SENDER_VERIFICATION_STATUSES,
} from "./email-delivery";

export {
  MARKETING_DELIVERABILITY_CHECK_IDS,
  MARKETING_DELIVERABILITY_CHECK_LABELS,
  MARKETING_DELIVERABILITY_FRESHNESS_MS,
  MARKETING_DELIVERABILITY_STATES,
  MARKETING_DELIVERABILITY_UNAVAILABLE_NOTICE,
  MARKETING_DNS_MUTATION_FORBIDDEN,
  MARKETING_SENDER_APPROVAL_STATUSES,
  MARKETING_SENDER_CAMPAIGN_CATEGORIES,
  MARKETING_SENDER_NOT_APPROVED,
  MARKETING_SENDER_SIMULATED_NOTICE,
  MARKETING_SENDER_SIMULATED_NOT_VERIFIED,
  MARKETING_SENDER_LIVE_NOT_VERIFIED,
  MARKETING_SENDER_AWAITING_PROVIDER_VERIFICATION,
  MARKETING_SENDER_VERIFY_EMAIL_FORBIDDEN,
  type MarketingDeliverabilityCheckId,
  type MarketingDeliverabilityState,
  type MarketingSenderApprovalStatus,
} from "./sender-deliverability";

export {
  MARKETING_FIXTURE_WEBHOOK_SIGNATURE_SCHEME,
  MARKETING_PROVIDER_CONTRACT_NOTICE,
  MARKETING_PROVIDER_ENGAGEMENT_EVENT_TYPES,
  MARKETING_PROVIDER_FAILURE_CATEGORIES,
  MARKETING_PROVIDER_LIVE_DISABLED,
  MARKETING_PROVIDER_RETRYABLE_FAILURES,
  MARKETING_PROVIDER_SEND_MODES,
  MARKETING_PROVIDER_SUPPRESSION_EVENT_TYPES,
  MARKETING_PROVIDER_WEBHOOK_EVENT_TYPES,
  MARKETING_WEBHOOK_ORG_ISOLATION,
  MARKETING_WEBHOOK_SIGNATURE_INVALID,
  MARKETING_WEBHOOK_SIGNATURE_MISSING,
} from "./provider-contracts";

export {
  MARKETING_DEFAULT_CHANNEL_ELIGIBILITY,
  MARKETING_WHATSAPP_DELIVERY_OUTCOMES,
  MARKETING_WHATSAPP_PROVIDER_ENV_KEYS,
  MARKETING_WHATSAPP_PROVIDER_TYPES,
  MARKETING_WHATSAPP_TEMPLATE_APPROVAL_STATES,
  MARKETING_WHATSAPP_TEMPLATE_CATEGORIES,
} from "./whatsapp-delivery";

export {
  MARKETING_DEFAULT_QUALIFICATION_POLICY,
  MARKETING_ENGAGEMENT_ONLY_INTENTS,
  MARKETING_EXPLICIT_INTENTS,
  MARKETING_GENUINE_RESPONSE_INTENTS,
  MARKETING_HANDOFF_PROCESS_STATES,
  MARKETING_QUALIFICATION_BUSINESS_STATES,
  MARKETING_QUALIFICATION_INBOX_STATUSES,
  MARKETING_QUALIFICATION_INBOX_STATUS_LABELS,
  MARKETING_QUALIFICATION_STATE_LABELS,
  MARKETING_RESPONSE_INTENTS,
} from "./qualification";

export {
  MARKETING_ROUTING_CRITERION_FIELDS,
  MARKETING_ROUTING_CRITERION_LABELS,
  MARKETING_ROUTING_MODES,
  type MarketingRoutingCriterionField,
} from "./routing";

export {
  MARKETING_DEFAULT_NOTIFICATION_CHANNELS,
  MARKETING_HANDOFF_REQUIRED_ACTION,
  MARKETING_NOTIFICATION_ATTEMPT_STATUSES,
  MARKETING_NOTIFICATION_CHANNELS,
  type MarketingNotificationAttemptStatus,
  type MarketingNotificationChannel,
} from "./notification";

export {
  MARKETING_ANALYTICS_RANGE_LABELS,
  MARKETING_ANALYTICS_RANGE_PRESETS,
  MARKETING_ANALYTICS_DEFAULT_PRESET,
  MARKETING_ANALYTICS_NOTICE,
  MARKETING_ENGAGEMENT_EVENT_TYPES,
  marketingChannelEventCapabilities,
} from "./analytics";

export {
  MARKETING_ASSET_ALLOWED_DOCUMENT_MIME_TYPES,
  MARKETING_ASSET_ALLOWED_IMAGE_MIME_TYPES,
  MARKETING_ASSET_ALLOWED_MIME_TYPES,
  MARKETING_ASSET_ALLOWED_VIDEO_MIME_TYPES,
  MARKETING_ASSET_APPROVAL_STATUSES,
  MARKETING_ASSET_DANGEROUS_EXTENSIONS,
  MARKETING_ASSET_DANGEROUS_MIME_TYPES,
  MARKETING_ASSET_DOCUMENT_REGISTRY_NOTICE,
  MARKETING_ASSET_FIXTURE_NOTICE,
  MARKETING_ASSET_FIXTURE_SCHEME,
  MARKETING_ASSET_IMAGE_BLOCK_TYPES,
  MARKETING_ASSET_PRODUCT_CATEGORIES,
  MARKETING_ASSET_STORAGE_PROVIDER,
  MARKETING_ASSET_TYPE_LABELS,
  MARKETING_ASSET_TYPES,
  MARKETING_SELECTED_ASSET_STORAGE_KEY,
  type MarketingAssetApprovalStatus,
  type MarketingAssetProductCategory,
  type MarketingAssetType,
} from "./assets";

export {
  MARKETING_ALWAYS_BLOCK_EMAIL_KINDS,
  MARKETING_CONSENT_CENTRE_NOTICE,
  MARKETING_CONSENT_CHANNELS,
  MARKETING_CONSENT_DURATIONS,
  MARKETING_CONSENT_RECORD_KIND_LABELS,
  MARKETING_CONSENT_RECORD_KINDS,
  MARKETING_CONSENT_RECORD_STATUSES,
  MARKETING_CONSENT_SOURCES,
  MARKETING_CONSENT_UNAVAILABLE_NOTICE,
  MARKETING_DEFAULT_CONSENT_GRANTED_VALUES,
  MARKETING_DEFAULT_SOFT_BOUNCE_TTL_MS,
  type MarketingConsentChannel,
  type MarketingConsentDuration,
  type MarketingConsentRecordKind,
  type MarketingConsentRecordStatus,
  type MarketingConsentSource,
} from "./consent-suppression";

export {
  MARKETING_COMMAND_CENTER_SECTIONS,
  type MarketingNavSection,
} from "./navigation";

export {
  MARKETING_ASSET_LIBRARY_PAGE_SIZE,
  MARKETING_REGISTRY_PAGE_SIZE,
  MARKETING_STATUS_NOT_COLOUR_ALONE,
  MARKETING_UX_BREAKPOINTS,
  MARKETING_UX_MAX_CLIENT_ROWS,
  MARKETING_UX_SKIP_LINK_LABEL,
  MARKETING_VISUAL_EDITOR_DESKTOP_NOTICE,
} from "./ux";

export {
  MARKETING_HOME_LIFECYCLE_CARDS,
  MARKETING_HOME_OUTCOME_CARDS,
  MARKETING_TEST_MODE_BANNER,
} from "./home-registry";

export {
  MARKETING_CAMPAIGN_MONITORING_LABELS,
  MARKETING_CAMPAIGN_MONITORING_NOTICE,
  MARKETING_CAMPAIGN_RECIPIENT_PAGE_SIZE,
  MARKETING_MONITORING_NEXT_ACTION_LABELS,
  MARKETING_MONITORING_RETRY_FORBIDDEN_NOTICE,
} from "./campaign-monitoring";

export {
  MARKETING_OPERATIONAL_HEALTH_NOTICE,
  MARKETING_OPERATIONAL_HEALTH_SIMULATED_NOTICE,
  MARKETING_RECOVERY_QUARANTINE_AFTER_ATTEMPTS,
  MARKETING_RETRY_BACKOFF_MS,
  MARKETING_NON_RETRYABLE_FAILURE_KINDS,
  MARKETING_RETRYABLE_FAILURE_KINDS,
} from "./recovery";

export {
  MARKETING_ATTRIBUTION_NOTICE,
  MARKETING_ATTRIBUTION_ROI_UNAVAILABLE,
  MARKETING_ATTRIBUTION_RULES,
  MARKETING_ATTRIBUTION_STAGE_LABELS,
} from "./attribution";

export {
  MARKETING_MONITORING_LABELS,
  MARKETING_MONITORING_NOTICE,
  MARKETING_RECIPIENT_EXPLORER_PAGE_SIZE,
} from "./monitoring";

export {
  MARKETING_PUBLIC_UNSUBSCRIBE_PATH,
  MARKETING_UNSUBSCRIBE_ALREADY_COPY,
  MARKETING_UNSUBSCRIBE_CHANNEL,
  MARKETING_UNSUBSCRIBE_CONFIRM_COPY,
  MARKETING_UNSUBSCRIBE_GENERIC_INVALID,
  MARKETING_UNSUBSCRIBE_SECRET_ENV,
  MARKETING_UNSUBSCRIBE_SUCCESS_COPY,
  MARKETING_UNSUBSCRIBE_TOKEN_TTL_MS,
  MARKETING_UNSUBSCRIBE_TOKEN_VERSION,
} from "./unsubscribe";

export {
  MARKETING_LIVE_ADAPTER_EXECUTION_BLOCKED,
  MARKETING_LIVE_ADAPTER_NOT_CONNECTED,
  MARKETING_LIVE_PROVIDER_DECISION_REQUIRED,
  MARKETING_LIVE_PROVIDER_NOTICE,
  MARKETING_LIVE_PROVIDER_STATUS,
  MARKETING_PROVIDER_CONNECT_BLOCKED,
  MARKETING_PROVIDER_VERIFICATION_AWAITING,
} from "./live-email-provider";

export {
  MARKETING_PHASE1_FROM_EMAIL,
  MARKETING_PHASE1_FROM_NAME,
  MARKETING_PHASE1_LIVE_RECIPIENT_CEILING,
  MARKETING_PHASE1_REPLY_TO,
  MARKETING_PHASE1_SMTP_MAX_CONCURRENT,
  MARKETING_SMTP_BLOCK,
  MARKETING_SMTP_DEFAULT_HOST,
  MARKETING_SMTP_ENV,
  MARKETING_SMTP_VERIFY_STATUSES,
  MARKETING_TEST_RECIPIENT_ALLOWLIST_ENV,
  MARKETING_SMTP_INBOX_DELIVERY_UNAVAILABLE,
  MARKETING_SMTP_PREFERRED_PORT,
} from "./hostinger-smtp";

export const ENTERPRISE_MARKETING_MODULE_ID = "enterprise-marketing-engine" as const;
export const ENTERPRISE_MARKETING_MODULE_TITLE = "Marketing Command Center" as const;
export const ENTERPRISE_MARKETING_ENGINE_NAME = "Enterprise Marketing Engine" as const;
